### PR TITLE
[AMAZON]: Fix issues when title is unset

### LINKED ISSUE #3745: Amazon Library only half populating, games listed as "???"
### Describe the bug

Heroic Launcher on a Steam Deck OLED is not pulling down my complete Amazon Games library.  Heroic appears to log into my Amazon account fine, and it shows the proper number of games in my library.  However, it only is pulling down information for about half my game library.  This problem appears to be unique to Amazon, as GOG and Epic do not have this issue.  I can guarantee that half my library is missing as I was looking to install The Banner Saga from my Amazon library, and while I can find the graphic for it in the grid view, it is listed as "???" and cannot be installed.

As far as troubleshooting goes, I have even gone so far as to completely wipe my Steam Deck by reinstalling the Steam Deck OS via USB to ensure there was no misconfiguration or previously tweaks I may have done that might cause an issue.

As you see in the following screenshot, when in list view, I have the proper count of games.  However as noted by the scroll bar indicator on the right, it's around the halfway mark that games start to populate appropriately.
List View

When switching to Grid View, you see that the first correctly populated game does have the game title listed correctly when you mouse over it.
Grid View - Good Game

However, then game directly before it that was listed as "???" in list view, does have the proper game graphics downloaded, but still it does not appear to have any further information like the game title.
Grid View - Bad Game

When I click on this game (or any game) marked as "???".  For a brief split second, I get an option to install, however the game title is still marked as "???"
Screenshot_20240510_093425

However, the screen quickly changes to this one in which clearing the Heroic cache or fully resetting does not help.
Screenshot_20240510_093637

### Add logs

```text
(09:47:48) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(09:47:48) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(09:47:48) INFO:    [Connection]:       Connectivity: check-online
(09:47:48) INFO:    [Connection]:       Pinging external endpoints
(09:47:48) INFO:    [Gog]:              Checking for existing gog manifests
(09:47:48) INFO:    [Nile]:             Refreshing library...
(09:47:48) INFO:    [Nile]:             Refreshing Amazon Games...
(09:47:48) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
(09:47:48) INFO:    [Nile]:             Game list updated, got 481 games
(09:47:48) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "status": "new",
    "title": "Widevine Content Decryption Module",
    "version": "4.10.2710.0"
  }
}
(09:47:49) WARNING: [Backend]:          Failed to register protocol with OS.
(09:47:49) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(09:47:49) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(09:47:49) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(09:47:49) INFO:    [Connection]:       Connectivity: online
(09:47:49) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(09:47:49) INFO:    [Backend]:          User Not Found, removing it from Store
(09:47:49) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(09:47:49) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(09:47:49) INFO:    [Backend]:          
System Information:
CPU: 8x AMD Custom APU 0932
Memory: 15.53 GB (used: 5.17 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Sephiroth [AMD Custom GPU 0405]
    IDs: D=1435 V=1002 SD=0123 SV=1002
    Driver: amdgpu
OS: SteamOS 3.5.19 holo (linux)

The current system is a Steam Deck (model: OLED) in desktop mode
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar

(09:47:49) INFO:    [Nile]:             Saved user data to config file
(09:47:49) INFO:    [Frontend]:         Refreshing undefined Library
(09:47:49) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(09:47:49) INFO:    [Legendary]:        Refreshing library...
(09:47:49) INFO:    [Nile]:             Refreshing library...
(09:47:49) INFO:    [Nile]:             Refreshing Amazon Games...
(09:47:49) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
(09:47:49) INFO:    [Nile]:             Game list updated, got 481 games
(09:47:49) INFO:    [Backend]:          Frontend Ready
(09:47:49) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(09:47:49) INFO:    [Nile]:             Looking for updates...
(09:47:49) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile list-updates --json
(09:47:50) INFO:    [Backend]:          Checking for current version changelog
(09:47:51) INFO:    [Winetricks]:       Downloading Winetricks
(09:47:53) INFO:    [WineDownloader]:   Updating wine versions info
(09:47:53) INFO:    [WineDownloader]:   Fetching upstream information...
(09:47:54) INFO:    [Backend]:          Starting the Download Queue
(09:47:55) INFO:    [WineDownloader]:   wine versions updated
```

### Steps to reproduce

Log in to Amazon account.
Only half of games library populates appropriately.
Reproducible every single time.  After experiencing the issue, I performed a Steam Deck factory reset via the Steam Deck menu.  Then after continuing to experience the issue, I performed a full Steam Deck OS re installation via USB and still experiencing the issue on a clean Steam Deck.

### Expected behavior

Full list of Amazon games with titles populated appropriately with the ability to install and run.

### Screenshots

_No response_

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]:Latest Stable version of Steam Deck OS.  Not using Beta or Preview builds.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by imLinguin**
Closes #3745 

From now on Nile will use game id as a name of directory.  
yes...

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

File: src/frontend/screens/Library/components/InstallModal/WineSelector/index.tsx [hunk 1]
```diff
@@ -62,9 +64,9 @@ export default function WineSelector({
         setWineVersion(wineVersion)
         setCrossoverBottle(defaultBottle)
       } else {
-        const sugestedWinePrefix = `${prefixFolder}/${removeSpecialcharacters(
-          title
-        )}`
+        const dirName =
+          removeSpecialcharacters(title) || removeSpecialcharacters(appName)
+        const sugestedWinePrefix = `${prefixFolder}/${dirName}`
```
Comment (CommandMC) [inline src/frontend/screens/Library/components/InstallModal/WineSelector/index.tsx:69]:
```suggestion
        const suggestedWinePrefix = `${prefixFolder}/${dirName}`
```
While you're at it

Comment (imLinguin) [reply src/frontend/screens/Library/components/InstallModal/WineSelector/index.tsx:69]: oh there is a typo hahaha

**Review by Etaash-mathamsetty — APPROVED** [review]
lgtm

**Review by CommandMC — APPROVED** [review]
