### PR TITLE
[FIX]: remember if window is maximized

### LINKED ISSUE #2850: Heroic refuses to start in a Maximized window
### Describe the bug

When i set Heroic's shortcut to start in fullscreen (Target field: `"C:\Users\<user>\AppData\Local\Programs\heroic\Heroic.exe" --start-fullscreen`) Heroic refuses to open maximized, and stays in an off-centered windowed mode 
image
Do you have to implement this flag, or am I using the wrong flag?

### Add logs

```text
17:27:59) INFO:    [Legendary]:        Refreshing library...

(17:27:59) INFO:    [Legendary]:        Refreshing Epic Games...

(17:27:59) INFO:    [Connection]:       Connectivity: check-online

(17:27:59) INFO:    [Connection]:       Pinging external endpoints

(17:27:59) INFO:    [Legendary]:        Running command: C:\Users\v\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version

(17:27:59) INFO:    [Legendary]:        Legendary location: C:\Users\v\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary

(17:27:59) INFO:    [Gog]:              GOGDL location: C:\Users\v\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl

(17:27:59) INFO:    [Gog]:              GOGDL location: C:\Users\v\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl

(17:27:59) INFO:    [Legendary]:        Game list updated, got 192 games & DLCs

(17:27:59) WARNING: [Backend]:          Protocol already registered.

(17:27:59) INFO:    [Connection]:       Connectivity: online

(17:28:00) INFO:    [Legendary]:        Running command: C:\Users\v\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party

(17:28:00) INFO:    [Gog]:              Running command: C:\Users\v\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\v\AppData\Roaming\heroic\gog_store\auth.json --version

(17:28:00) INFO:    [Backend]:          VCRuntime is installed

(17:28:00) INFO:    [Backend]:          Loading Screen Ready

(17:28:00) INFO:    [Frontend]:         Refreshing undefined Library

(17:28:00) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager

(17:28:00) INFO:    [Gog]:              Found 0 game(s) to update

(17:28:00) INFO:    [Backend]:          Frontend Ready

(17:28:00) INFO:    [Backend]:          Checking for new Heroic Updates

(17:28:00) INFO:    [Backend]:          Checking for current version changelog

(17:28:00) INFO:    [Legendary]:        Checking for game updates: C:\Users\v\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party

(17:28:02) INFO:    [Legendary]:        Found 0 games to update

(17:28:04) INFO:    [Backend]:          

Heroic Version: 2.8.0 Nico Robin

Legendary Version:  0.20.32 Dark Energy (hotfix #6)

GOGdl Version: 0.7.2

Electron Version: 23.1.4

Chrome Version: 110.0.5481.192

NodeJS Version: 18.12.1

OS: Microsoft Windows 11 Pro KERNEL: 10.0.22621 ARCH: x64

CPU: Intel Gen Intel® Core™ i5-11400F @2.6 

RAM: Total: 15.84 GiB Available: 2.76 GiB

GRAPHICS: GPU0: NVIDIA GeForce RTX 3060 VRAM: 12288MB DRIVER: 536.40

(17:28:05) INFO:    [Backend]:          Starting the Download Queue

(17:28:06) DEBUG:   [Legendary]:        Using cached install info

(17:28:06) INFO:    [Legendary]:        Updating 7786b355a13b47a6b3915335117cd0b2: C:\Users\v\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary update 7786b355a13b47a6b3915335117cd0b2 -y

(17:28:06) DEBUG:   [Legendary]:        Logging to file "C:\Users\v\AppData\Roaming\heroic\GamesConfig\7786b355a13b47a6b3915335117cd0b2.log"

(17:28:06) INFO:    [Backend]:          Preventing machine to sleep

(17:28:07) INFO:    [DownloadManager]:  Finished Update of 7786b355a13b47a6b3915335117cd0b2

(17:28:07) INFO:    [DownloadManager]:  7786b355a13b47a6b3915335117cd0b2 added to download manager finished.

(17:28:07) INFO:    [DownloadManager]:  7786b355a13b47a6b3915335117cd0b2 removed from download manager.

(17:28:07) INFO:    [Frontend]:         Refreshing legendary Library

(17:28:07) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager

(17:28:07) INFO:    [Gog]:              Found 0 game(s) to update

(17:28:07) INFO:    [Backend]:          operation interrupted

(17:28:08) INFO:    [Legendary]:        Checking for game updates: C:\Users\v\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party

(17:28:09) INFO:    [Legendary]:        Found 0 games to update
```

### Steps to reproduce

1. Rightclick `Heroic.exe`
2. Click on `create shortcut`
3. move shortcut anywhere you want (I used `%USERPROFILE%` and `Desktop`)
4. Rightclick > edit shortcut
5. in target field, add `--start-fullscreen`
6. Save
7. Double-click shortcut
8. Heroic opens normally, not maximized

OR

1. press `Win + R`
2. input `"%localappdata%\programs\heroic\heroic.exe" --start-fullscreen`
3. Press `Enter`, or click `OK`
4. Heroic opens, not maximized

### Expected behavior

open Heroic in fullscreen

### Screenshots

Off-centered Heroic (THIS IS NORMAL BEHAVIOUR, NOT BUG)
image

### Heroic Version

Latest Stable

### System Information

Windows 11 Pro

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by imLinguin**
Closes #2850

One small thing though, window will not remember it's original size in non-maximized state, as this is behaviour of getBounds 

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

File: src/common/types/electron_store.ts [hunk 1]
```diff
@@ -40,7 +41,7 @@ export interface StoreStructure {
       gogdlLogFile: string
       nileLogFile: string
     }
-    'window-props': Electron.Rectangle
+    'window-props': WindowProps
```
Comment (CommandMC) [inline src/common/types/electron_store.ts:44]: In general, altering types of a store isn't that great of an idea (since the underlying data of course doesn't change, so you're still getting the old type even though you think you're getting the new one)
This isn't *that bad* here (the only missing prop. is "maximized", and it being `undefined` has the same effect as it just being `false`), but it's something to keep in mind

**Review by CommandMC — APPROVED** [review]

File: src/common/types/electron_store.ts (hunk 1 above)
Comment (imLinguin) [reply src/common/types/electron_store.ts:44]: Oh yes that's clear, normally we'd add some code that sort of migrates the config. But like you mentioned it's not required in this case
