### PR TITLE
[Tech] Eslint Updates + Fix GOG Installing

### LINKED ISSUE #1251: Cancelling GOG games installation show game as installed
### Describe the bug

When cancelling the installation of a GOG game, the installation is canceled, but the game status is updated as installed. It can be "uninstalled" sometimes but sometimes uninstalling the game fails because it can't find files to uninstall.

### Add logs

Not relevant, the log shows that the installation process got killed as expected.

### Steps to reproduce

1. Open the GOG library
2. Start installing a game
3. After a moment, cancel the installation
4. Game shows as installed
5. Try to uninstall it, sometimes it will work and the game status changes to not installed, but sometimes it fails to uninstall

### Expected behavior

Cancelling the installation should work like the epic library, it should NOT add the game in the installed games store.

### Screenshots

_No response_

### System Information

- OS [e. g. "Ubuntu"]: Not relevant
- Heroic Version [e. g. 2.1.1]: Main branch

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by flavioislima**
This will add two new rules:
```
"@typescript-eslint/return-await"
"@typescript-eslint/promise-function-async"
```

So we can check the proper usage of `async`, `await` and `Promises` in general.
also fixes #1251 introduced by some refactor.

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by arielj** [comment]
The GOG fix is not working for me, I started installed a game, cancelled the installation, and the game state changed to installed.

I'll try to debug it a big to give more details.

File: electron/gog/games.ts [hunk 1]
```diff
@@ -139,52 +139,51 @@ class GOGGame extends Game {
 
     logInfo([`Installing ${this.appName} with:`, command], LogPrefix.Gog)
 
-    const res = await runGogdlCommand(commandParts, logPath)
-
-    if (res.error) {
+    try {
```
Comment (arielj) [inline electron/gog/games.ts:142]: this try is not doing what's expected, the runGogdlCommand already uses a try catch and it's swallowing this exception and it returns an object (that's why the previous code uses `re.error`)

I think we need to re-throw the exception in the catch inside runGogdlCommand

Comment (arielj) [reply electron/gog/games.ts:142]: hmmm after more debugging, the cancellation kills the process but that's triggering the `child.on('close'...` callback that resolves the promise, it's like... javascript things that everything is fine, that the process finished and not that it was killed

Comment (arielj) [reply electron/gog/games.ts:142]: looks like this is what fixes the problem, inside runGogdlCommand, change the `close` callback to this:

```ts
    child.on('close', (code) => {
      if (code === 0) {
        res({
          stdout: stdout.join('\n'),
          stderr: stderr.join('\n')
        })
      } else {
        rej('Process finished with non-zero exit code')
      }
    })
```

So this way, when the process is killed, a non-zero status code is returned and we know it was not successfull.

Then in the `.catch` call in that same method do:

```ts
    .catch((error) => {
      logError(
        [`Error running GOGDL command "${safeCommand}": ${error}`],
        LogPrefix.Legendary
      )
      throw error
    })
```

instead of returning an object, so it triggers the try/catch on the caller

Comment (flavioislima) [reply electron/gog/games.ts:142]: Weird that I tried this fix on Linux and Mac and it worked. I will this other approach then.

Comment (flavioislima) [reply electron/gog/games.ts:142]: Changing this line:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/b8b1ed0d1647e2a660eaf865a6f1da2f7b5d7482/electron/gog/library.ts#L657

Didn't work for me. And now my previous solution is also not working 🤔

Comment (flavioislima) [reply electron/gog/games.ts:142]: Even when canceling the `code` comes `0`. Pretty weird

Comment (flavioislima) [reply electron/gog/games.ts:142]: The issue started with this commit: 756a1e728800371b799d56cbc62201f70d1e8d40
on PR #1092.
I believe Spawn for some reason thinks everything is fine even though sometimes it shows that an error has occurred. So since on GOG `intalled.json` is written by Heroic, it writes the info although the files were not written.

Comment (flavioislima) [reply electron/gog/games.ts:142]: Instead of checking the code, checking for `signal` seems to fix it:
```
    child.on('close', (code, signal) => {
      console.log({ code, signal })
      if (signal === 'SIGTERM') {
        rej('error')
      }
      res({
        stdout: stdout.join('\n'),
        stderr: stderr.join('\n')
      })
    })
```

Comment (arielj) [reply electron/gog/games.ts:142]: great! maybe the exit code is not consistent through different OSes? the signal sounds like the safest solution!

Comment (flavioislima) [reply electron/gog/games.ts]: Updated the branch, test again when you have the time.

**Comment by arielj** [comment]
tested with the latest changes, cancellation works fine now!

one thing I noticed (but I don't know if it's a gogdl thing or heroic) is that, when I cancel the installation, if I chose to NOT keep the downloaded parts, I see an error in the console, if I chose to keep the downloaded parts I don't have an error

```
(14:11:30) INFO:    [Gog]:             Installing 1356485086 with: /home/ariel/dev/oss/HeroicGamesLauncher/public/bin/linux/gogdl download 1356485086 --platform linux --path=/home/ariel/Games/Heroic RIQ-Eyug7BbAdzAuTZBTg-b5KE3krkrlLEilNS2Z3uMuZnrYoLSiVp5uA5yb7gOedVoxa2_nU-kj51DkERCj8E61nx4RZIr0f2hlf7ndm1humSAwN7morM9vktJ6453IPUFCtqVf8HGVIjqI1b_OhLP4M-uwy7HPC2QiWOsuxOp81-Mzs8PX_a3SKX7imwMg --skip-dlcs --lang=en
(14:11:30) DEBUG:   [Gog]:             Running GOGDL command: /home/ariel/dev/oss/HeroicGamesLauncher/public/bin/linux/gogdl download 1356485086 --platform linux --path=/home/ariel/Games/Heroic RIQ-Eyug7BbAdzAuTZBTg-b5KE3krkrlLEilNS2Z3uMuZnrYoLSiVp5uA5yb7gOedVoxa2_nU-kj51DkERCj8E61nx4RZIr0f2hlf7ndm1humSAwN7morM9vktJ6453IPUFCtqVf8HGVIjqI1b_OhLP4M-uwy7HPC2QiWOsuxOp81-Mzs8PX_a3SKX7imwMg --skip-dlcs --lang=en
(14:11:30) DEBUG:   [Gog]:             Logging to file "/home/ariel/.config/heroic/GamesConfig/1356485086.log"
(14:11:31) INFO:    [Backend]:         Progress for 1356485086: /MiB/
(14:11:32) INFO:    [Backend]:         Progress for 1356485086: /MiB/
(14:11:34) INFO:    [Backend]:         Progress for 1356485086: 1.08/6.00MiB/00:03:01
(14:11:35) INFO:    [Backend]:         Progress for 1356485086: 2.16/12.00MiB/00:03:02
(14:11:37) INFO:    [Backend]:         Progress for 1356485086: 4.50/25.00MiB/00:03:04
(14:11:38) INFO:    [Backend]:         Progress for 1356485086: 5.76/32.00MiB/00:03:05
(14:11:40) INFO:    [Backend]:         Progress for 1356485086: 8.10/45.00MiB/00:05:07
(14:11:41) INFO:    [Gog]:             killing 1356485086
(14:11:41) INFO:    [Gog]:             1356485086 killed
(14:11:41) ERROR:   [Legendary]:       Error running GOGDL command "/home/ariel/dev/oss/HeroicGamesLauncher/public/bin/linux/gogdl download 1356485086 --platform linux --path=/home/ariel/Games/Heroic RIQ-Eyug7BbAdzAuTZBTg-b5KE3krkrlLEilNS2Z3uMuZnrYoLSiVp5uA5yb7gOedVoxa2_nU-kj51DkERCj8E61nx4RZIr0f2hlf7ndm1humSAwN7morM9vktJ6453IPUFCtqVf8HGVIjqI1b_OhLP4M-uwy7HPC2QiWOsuxOp81-Mzs8PX_a3SKX7imwMg --skip-dlcs --lang=en": error
(14:11:41) ERROR:   [Gog]:             Failed to install 1356485086: error
(14:11:41) INFO:    [Backend]:         finished installing
(14:11:41) INFO:    [Frontend]:        Refreshing Library
(14:11:41) INFO:    [Legendary]:       Refreshing library...
(14:11:41) INFO:    [Gog]:             Getting GOG library
(14:11:41) INFO:    [Legendary]:       Updating game list
(14:11:41) INFO:    [Legendary]:       Game List Updated
(14:11:42) INFO:    [Gog]:             Number of library pages: 1
(14:11:42) INFO:    [Gog]:             Saved games data
(14:11:43) ERROR:   [Backend]:         Error: ENOENT: no such file or directory, stat '/home/ariel/Games/Heroic/Brigador Up-Armored Edition'
```

In both cases the log is similar, except for the last line there with the missing file/directory (it only shows up if I cancel the installation and chose to NOT keep the downloaded parts)

But maybe we can ignore that in this PR since the main issue is actually fixed.

File: electron/gog/library.ts [hunk 2]
```diff
@@ -654,7 +654,10 @@ export async function runGogdlCommand(
       stderr.push(data.toString().trim())
     })
 
-    child.on('close', () => {
+    child.on('close', (code, signal) => {
+      if (signal === 'SIGTERM') {
+        rej('error')
```
Comment (arielj) [inline electron/gog/library.ts:659]: Maybe reject with `'Installation canceled'`?

**Review by arielj — DISMISSED** [review]
I added one comment on the reject error message, but this fix works as expected.

about the async related changed, I understand it's all related to the new eslint rule, it touches a lot of files so I don't know if that affects the app in any way, I didn't test things other than cencelling the gog games

**Comment by flavioislima** [comment]
@arielj this error message it is like it is trying to remove the folder that `gogdl` already deleted, but I might be wrong here. @imLinguin might now better.

About the async/await changes, that is not affecting the app, I tested it in several ways. The problem is that in several places we were using those without need and in other we were forgetting to add. So this rule simply fixes that.

**Comment by imLinguin** [comment]
If it's a native game, gogdl downloads everything into `.cache/heroicGOGdl` or `$XDG_CACHE_HOME/heroicGOGdl` there unpacks game installer and moves all game files to the desired location. We should probably remove directory I mentioned when install is cancelled

**Comment by arielj** [comment]
> If it's a native game, gogdl downloads everything into `.cache/heroicGOGdl` or `$XDG_CACHE_HOME/heroicGOGdl` there unpacks game installer and moves all game files to the desired location. We should probably remove directory I mentioned when install is cancelled

can confirm that the error about the missing file happens only with a native game

**Comment by flavioislima** [comment]
> If it's a native game, gogdl downloads everything into `.cache/heroicGOGdl` or `$XDG_CACHE_HOME/heroicGOGdl` there unpacks game installer and moves all game files to the desired location. We should probably remove directory I mentioned when install is cancelled

OK, for now I wont touch this logic. We can fix it later since its not affecting anything.
