### PR TITLE
[macOS] Fix install progress, install failling and no space error message

### LINKED ISSUE #967: Warning for "not enough disk space" does not appear on macOS
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
So, what happens is that I'm on a Mac, trying to download Hitman™ but it seems that it can't get the Download Size and/or Install Size meaning that when I press Download, it stalls for like 3s (saying "Installing 0%...") then it says the download was complete, when it wasn't.

I think it's because since it can't calculate Download Size or Install Size, it thinks the game has been downloaded. It only happens on Hitman™ therefor making the game uninstallable

**To Reproduce**

1. Log into an account that has Hitman™ on it.
2. Go to the Library
3. Click on HITMAN
4. Click Install
5. Wait for like 5s
6. Witness bug

**Expected behavior**
Game is supposed to install.

**Screenshots**
Screenshot 2022-02-08 at 7 48 06 PM

**Desktop (please complete the following information):**

- OS: macOS 11
- Heroic Version: 2.1.1
- Game: Hitman™
- Wine/Proton version: CrossOver
- Hardware specs (RAM, CPU, GPU): M1

**Additional context**

### LINKED ISSUE #1170: [MacOS] No Progress is Shown when installing games
```
(17:59:35) INFO:    [Legendary]:       Location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary
(17:59:35) INFO:    [Gog]:             Location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl
(17:59:47) INFO:    [Backend]:         
  Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: macOS KERNEL: 21.3.0 ARCH: x64
  CPU: Apple M1 Pro @2.4 
  RAM: Total: 34.4 GB Available: 22.8 GB
  GRAPHICS: GPU0: Apple M1 Pro VRAM: nullMB DRIVER:  
  
  
(17:59:47) WARNING: [Backend]:         Protocol already registered.
(17:59:49) INFO:    [Frontend]:        Refreshing Library
(17:59:49) INFO:    [Legendary]:       Refreshing library...
(17:59:49) INFO:    [Legendary]:       Refreshing Epic Games...
(17:59:49) INFO:    [Legendary]:       Refreshing Epic Games...
(17:59:53) INFO:    [Legendary]:       [cli] INFO: Logging in...
(17:59:53) INFO:    [Legendary]:       [Core] INFO: Trying to re-use existing login session...
(17:59:54) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(17:59:55) INFO:    [Backend]:         checking for heroic updates
(17:59:55) INFO:    [Legendary]:       Getting More details with Legendary info command... 
(17:59:56) INFO:    [Legendary]:       Getting More details with Legendary info command... 
(17:59:57) INFO:    [Legendary]:       Updating game list
(17:59:58) INFO:    [Legendary]:       Game List Updated
(18:00:10) INFO:    [Legendary]:       Checking for game updates
(18:00:10) INFO:    [Legendary]:       Found 0 game(s) to update
(18:00:10) INFO:    [Gog]:             Found 0 game(s) to update
(18:00:10) INFO:    [Legendary]:       Getting More details with Legendary info command... 
(18:00:13) INFO:    [Legendary]:       Getting More details with Legendary info command... 
(18:00:13) INFO:    [Legendary]:       Installing Sugar with: legendary install Sugar --platform Windows --base-path '/Users/bailey/Games/Heroic' --skip-dlcs --skip-sdl  -y |& tee "/Users/bailey/Library/Application Support/heroic/GamesConfig/Sugar.log"
(18:00:13) INFO:    [Legendary]:       Getting More details with Legendary info command... 
(18:00:15) INFO:    [Backend]:         Progress: Sugar /MiB/undefined
```
Install hangs and progress bar never fills up. Trying to download rocket league.

### PR DESCRIPTION
**Pull request by flavioislima**
Fix a regression that made GOG games fail to install on macOS as well.
Fix #1170
Fix #967  (probably, since the logs could not be accessed since the path was wrong due to having spaces on mac)
Add #1211
Got rid of `react-context-menu` that is deprecated and created a new component for that using MUI.

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [x] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

File: electron/gog/library.ts [hunk 1]
```diff
@@ -632,7 +632,11 @@ export async function runGogdlCommand(
   }
 
   return new Promise((res, rej) => {
-    const child = spawn(bin, commandParts, { cwd: dir, env: env })
+    const child = spawn(bin, commandParts, {
+      cwd: dir,
+      env: env,
+      shell: getShell()
```
Comment (CommandMC) [inline electron/gog/library.ts:638]: Are you sure this doesn't bring back the quote issues?

It might be better to really only run in a shell if we're on MacOS
So
```suggestion
      shell: isMac
```

File: electron/legendary/games.ts [hunk 2]
```diff
@@ -302,7 +302,7 @@ class LegendaryGame extends Game {
     const withDlcs = installDlcs ? '--with-dlcs' : '--skip-dlcs'
     const installSdl = sdlList.length ? this.getSdlList(sdlList) : '--skip-sdl'
 
-    const logPath = `${join(heroicGamesConfigPath, this.appName + '.log')}`
+    const logPath = `"${join(heroicGamesConfigPath, this.appName + '.log')}"`
```
Comment (CommandMC) [inline electron/legendary/games.ts]: Interesting how the quotes are required here. I would've thought that a Node-internal function (like `appendFile`) wouldn't need those

Comment (CommandMC) [reply electron/legendary/games.ts]: Ah, you removed the quotes in a later commit
Whoops

Comment (flavioislima) [reply electron/legendary/games.ts]: Yes, I noticed that we just need them when reading the path, so I removed them when declaring.
