### PR TITLE
[MISC]: prettify discord rich presence

### LINKED ISSUE #2869: Better Discord RPC design
### Problem description

current RPC just blasts heroic as the main thing, overshadowing the game you are playing

### Feature description

it would be better to use the game's poster image/icon for the big icon and have Heroic's icon as a small icon

also instead of the Playing/main title being "Heroic Games Launcher" it could be the game's title, while Heroic Games Launcher being on the second line under it

I'm positive this can be done and shouldn't be too much effort, also I believe it's just a better design overall that actually showcases what you are playing immediately, while there's still Heroic mentioned

alternatively instead of "via Heroic on Linux" it could be 2 lines
"Heroic Games Launcher"
"on Linux"

same way you grab poster images for games for the library, you could probably get an icon

the current RPC design should be used when there isn't an icon to be found

### Alternatives

#2177

### Additional information

Current rich presence:

Screenshot from 2023-07-19 12-29-02

Example presence with the feature mentioned:

Screenshot from 2023-07-19 12-29-28

Proposed rich presence design:

Screenshot from 2023-07-19 12-37-12

### LINKED ISSUE #3179: Discord Rich Presence shows the launcher, not the game
### Describe the bug

image

As you can see, the presence info on the user shows "Playing Heroic Games Launcher".  
The game info is clearly being sent to Discord as the profile page shows Rocket League.

### Add logs

```text
(16:11:55) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(16:11:55) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(16:11:55) INFO:    [Connection]:       Connectivity: check-online
(16:11:55) INFO:    [Connection]:       Pinging external endpoints
(16:11:55) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2710.0"
  }
}
(16:11:56) WARNING: [Backend]:          Protocol already registered.
(16:11:56) INFO:    [Connection]:       Connectivity: online
(16:11:56) INFO:    [Gog]:              Checking if login is valid
(16:11:56) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/richard/.config/heroic/gog_store/auth.json auth
(16:11:56) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(16:11:56) INFO:    [Backend]:          Loading Screen Ready
(16:11:56) INFO:    [Frontend]:         Refreshing undefined Library
(16:11:56) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(16:11:56) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/richard/.config/heroic/gog_store/auth.json auth
(16:11:56) INFO:    [Legendary]:        Refreshing library...
(16:11:56) INFO:    [Legendary]:        Refreshing Epic Games...
(16:11:56) INFO:    [Legendary]:        Game list updated, got 11 games & DLCs
(16:11:56) INFO:    [Backend]:          Frontend Ready
(16:11:56) INFO:    [Backend]:          Checking for new Heroic Updates
(16:11:56) INFO:    [Backend]:          Checking for current version changelog
(16:11:56) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/richard/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(16:11:56) INFO:    [Gog]:              Getting GOG library
(16:11:56) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/richard/.config/heroic/gog_store/auth.json auth
(16:11:56) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/richard/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(16:11:56) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/richard/.config/heroic/gog_store/auth.json --version
(16:11:56) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/richard/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(16:11:56) INFO:    [Backend]:          
System Information:
CPU: 16x AMD Ryzen 7 5800X 8-Core Processor
Memory: 67.34 GB (used: 14.29 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation GA104 [GeForce RTX 3060]
    IDs: D=2487 V=10de SD=4074 SV=1458
    Driver: nvidia
OS: Manjaro Linux 6.1.55-1-MANJARO (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.9.2 Boa Hancock
  Legendary: 0.20.32 Dark Energy (hotfix #6)
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar

(16:11:56) INFO:    [Gog]:              Saved username to config file
(16:11:57) INFO:    [Gog]:              Saved games data
(16:11:57) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(16:11:57) INFO:    [Gog]:              Found 0 game(s) to update
(16:11:57) INFO:    [Legendary]:        Checking for game updates: XDG_CONFIG_HOME=/home/richard/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(16:11:57) INFO:    [Backend]:          Launching Rocket League® (Sugar)
(16:11:57) INFO:    [Backend]:          Preventing display from sleep
(16:11:57) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(16:11:58) INFO:    [Backend]:          Preventing machine to sleep
(16:11:58) INFO:    [Backend]:          Stopping Power Saver Blocker
(16:11:58) INFO:    [Backend]:          Started Discord Rich Presence
(16:11:58) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(16:11:58) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(16:11:58) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(16:11:58) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-8.1!
Missing undefined and/or undefined!
Falling back to system libraries!
(16:11:58) DEBUG:   [Backend]:          Running Wine command: wineboot --init
(16:11:58) INFO:    [Winetricks]:       Downloading Winetricks
(16:11:58) INFO:    [Legendary]:        Found 0 games to update
(16:12:01) INFO:    [Backend]:          Starting the Download Queue
(16:12:02) INFO:    [DXVKInstaller]:    installing dxvk on... /home/richard/Games/Heroic/Prefixes/Rocket League
(16:12:02) INFO:    [DXVKInstaller]:    dxvk already installed!
(16:12:02) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-8.1!
Missing undefined and/or undefined!
Falling back to system libraries!
(16:12:02) INFO:    [Legendary]:        Launching Rocket League®: DOTNET_BUNDLE_EXTRACT_BASE_DIR= HEROIC_APP_NAME=Sugar HEROIC_APP_RUNNER=legendary HEROIC_APP_SOURCE=epic LD_PRELOAD= WINEPREFIX="/home/richard/Games/Heroic/Prefixes/Rocket League" WINEDLLOVERRIDES=winemenubuilder.exe=d WINE_FULLSCREEN_FSR=0 WINEESYNC=1 WINEFSYNC=1 ORIG_LD_LIBRARY_PATH= XDG_CONFIG_HOME=/home/richard/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Sugar --wine /usr/bin/wine --language en
(16:19:02) INFO:    [Backend]:          Stopped Discord Rich Presence
(16:19:02) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(16:19:02) INFO:    [Frontend]:         Refreshing legendary Library
(16:19:02) INFO:    [Legendary]:        Refreshing library...
(16:19:02) INFO:    [Legendary]:        Refreshing Epic Games...
(16:19:02) INFO:    [Legendary]:        Game list updated, got 11 games & DLCs
(16:19:02) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/richard/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(17:00:51) INFO:    [Backend]:          Launching Rocket League® (Sugar)
(17:00:51) INFO:    [Backend]:          Preventing display from sleep
(17:00:51) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(17:00:51) INFO:    [Backend]:          Stopping Power Saver Blocker
(17:00:51) INFO:    [Backend]:          Started Discord Rich Presence
(17:00:51) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(17:00:51) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(17:00:51) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(17:00:51) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-8.1!
Missing undefined and/or undefined!
Falling back to system libraries!
(17:00:51) DEBUG:   [Backend]:          Running Wine command: wineboot --init
(17:00:55) INFO:    [DXVKInstaller]:    installing dxvk on... /home/richard/Games/Heroic/Prefixes/Rocket League
(17:00:55) INFO:    [DXVKInstaller]:    dxvk already installed!
(17:00:55) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-8.1!
Missing undefined and/or undefined!
Falling back to system libraries!
(17:00:55) INFO:    [Legendary]:        Launching Rocket League®: DOTNET_BUNDLE_EXTRACT_BASE_DIR= HEROIC_APP_NAME=Sugar HEROIC_APP_RUNNER=legendary HEROIC_APP_SOURCE=epic LD_PRELOAD= WINEPREFIX="/home/richard/Games/Heroic/Prefixes/Rocket League" WINEDLLOVERRIDES=winemenubuilder.exe=d WINE_FULLSCREEN_FSR=0 WINEESYNC=1 WINEFSYNC=1 ORIG_LD_LIBRARY_PATH= XDG_CONFIG_HOME=/home/richard/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Sugar --wine /usr/bin/wine --language en
(22:06:23) INFO:    [Backend]:          Stopped Discord Rich Presence
(22:06:23) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(22:06:23) INFO:    [Frontend]:         Refreshing legendary Library
(22:06:23) INFO:    [Legendary]:        Refreshing library...
(22:06:23) INFO:    [Legendary]:        Refreshing Epic Games...
(22:06:23) INFO:    [Legendary]:        Game list updated, got 11 games & DLCs
(22:06:23) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/richard/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(22:56:47) INFO:    [Backend]:          Launching Rocket League® (Sugar)
(22:56:47) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(22:56:47) INFO:    [Backend]:          Stopping Power Saver Blocker
(22:56:47) INFO:    [Backend]:          Started Discord Rich Presence
(22:56:47) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(22:56:47) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(22:56:47) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(22:56:47) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-8.1!
Missing undefined and/or undefined!
Falling back to system libraries!
(22:56:47) DEBUG:   [Backend]:          Running Wine command: wineboot --init
(22:56:51) INFO:    [DXVKInstaller]:    installing dxvk on... /home/richard/Games/Heroic/Prefixes/Rocket League
(22:56:51) INFO:    [DXVKInstaller]:    dxvk already installed!
(22:56:51) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-8.1!
Missing undefined and/or undefined!
Falling back to system libraries!
(22:56:51) INFO:    [Legendary]:        Launching Rocket League®: DOTNET_BUNDLE_EXTRACT_BASE_DIR= HEROIC_APP_NAME=Sugar HEROIC_APP_RUNNER=legendary HEROIC_APP_SOURCE=epic LD_PRELOAD= WINEPREFIX="/home/richard/Games/Heroic/Prefixes/Rocket League" WINEDLLOVERRIDES=winemenubuilder.exe=d WINE_FULLSCREEN_FSR=0 WINEESYNC=1 WINEFSYNC=1 ORIG_LD_LIBRARY_PATH= XDG_CONFIG_HOME=/home/richard/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Sugar --wine /usr/bin/wine --language en
(23:11:18) INFO:    [Backend]:          Stopped Discord Rich Presence
(23:11:18) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(23:11:18) INFO:    [Frontend]:         Refreshing legendary Library
(23:11:18) INFO:    [Legendary]:        Refreshing library...
(23:11:18) INFO:    [Legendary]:        Refreshing Epic Games...
(23:11:18) INFO:    [Legendary]:        Game list updated, got 11 games & DLCs
(23:11:18) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/richard/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(17:47:37) INFO:    [Backend]:          Launching Rocket League® (Sugar)
(17:47:37) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(17:47:37) INFO:    [Backend]:          Stopping Power Saver Blocker
(17:47:37) INFO:    [Backend]:          Started Discord Rich Presence
(17:47:37) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(17:47:37) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(17:47:37) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(17:47:37) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-8.1!
Missing undefined and/or undefined!
Falling back to system libraries!
(17:47:37) DEBUG:   [Backend]:          Running Wine command: wineboot --init
(17:47:41) INFO:    [DXVKInstaller]:    installing dxvk on... /home/richard/Games/Heroic/Prefixes/Rocket League
(17:47:41) INFO:    [DXVKInstaller]:    dxvk already installed!
(17:47:41) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-8.1!
Missing undefined and/or undefined!
Falling back to system libraries!
(17:47:41) INFO:    [Legendary]:        Launching Rocket League®: DOTNET_BUNDLE_EXTRACT_BASE_DIR= HEROIC_APP_NAME=Sugar HEROIC_APP_RUNNER=legendary HEROIC_APP_SOURCE=epic LD_PRELOAD= WINEPREFIX="/home/richard/Games/Heroic/Prefixes/Rocket League" WINEDLLOVERRIDES=winemenubuilder.exe=d WINE_FULLSCREEN_FSR=0 WINEESYNC=1 WINEFSYNC=1 ORIG_LD_LIBRARY_PATH= XDG_CONFIG_HOME=/home/richard/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Sugar --wine /usr/bin/wine --language en
(19:03:04) INFO:    [Backend]:          Stopped Discord Rich Presence
(19:03:04) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(19:03:04) INFO:    [Frontend]:         Refreshing legendary Library
(19:03:04) INFO:    [Legendary]:        Refreshing library...
(19:03:04) INFO:    [Legendary]:        Refreshing Epic Games...
(19:03:04) INFO:    [Legendary]:        Game list updated, got 11 games & DLCs
(19:03:05) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/richard/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(19:59:04) INFO:    [Backend]:          Launching Rocket League® (Sugar)
(19:59:04) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(19:59:04) INFO:    [Backend]:          Stopping Power Saver Blocker
(19:59:04) INFO:    [Backend]:          Started Discord Rich Presence
(19:59:04) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(19:59:04) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(19:59:04) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(19:59:04) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-8.1!
Missing undefined and/or undefined!
Falling back to system libraries!
(19:59:04) DEBUG:   [Backend]:          Running Wine command: wineboot --init
(19:59:08) INFO:    [DXVKInstaller]:    installing dxvk on... /home/richard/Games/Heroic/Prefixes/Rocket League
(19:59:08) INFO:    [DXVKInstaller]:    dxvk already installed!
(19:59:08) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-8.1!
Missing undefined and/or undefined!
Falling back to system libraries!
(19:59:08) INFO:    [Legendary]:        Launching Rocket League®: DOTNET_BUNDLE_EXTRACT_BASE_DIR= HEROIC_APP_NAME=Sugar HEROIC_APP_RUNNER=legendary HEROIC_APP_SOURCE=epic LD_PRELOAD= WINEPREFIX="/home/richard/Games/Heroic/Prefixes/Rocket League" WINEDLLOVERRIDES=winemenubuilder.exe=d WINE_FULLSCREEN_FSR=0 WINEESYNC=1 WINEFSYNC=1 ORIG_LD_LIBRARY_PATH= XDG_CONFIG_HOME=/home/richard/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Sugar --wine /usr/bin/wine --language en
(23:53:35) INFO:    [Backend]:          Stopped Discord Rich Presence
(23:53:35) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(23:53:35) INFO:    [Frontend]:         Refreshing legendary Library
(23:53:35) INFO:    [Legendary]:        Refreshing library...
(23:53:35) INFO:    [Legendary]:        Refreshing Epic Games...
(23:53:35) INFO:    [Legendary]:        Game list updated, got 11 games & DLCs
(23:53:35) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/richard/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(13:39:19) INFO:    [Backend]:          Launching Rocket League® (Sugar)
(13:39:19) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(13:39:19) INFO:    [Backend]:          Started Discord Rich Presence
(13:39:19) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(13:39:19) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(13:39:19) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(13:39:19) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-8.1!
Missing undefined and/or undefined!
Falling back to system libraries!
(13:39:19) DEBUG:   [Backend]:          Running Wine command: wineboot --init
(13:39:19) INFO:    [Backend]:          Stopping Power Saver Blocker
(13:39:23) INFO:    [DXVKInstaller]:    installing dxvk on... /home/richard/Games/Heroic/Prefixes/Rocket League
(13:39:23) INFO:    [DXVKInstaller]:    dxvk already installed!
(13:39:23) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-8.1!
Missing undefined and/or undefined!
Falling back to system libraries!
(13:39:23) INFO:    [Legendary]:        Launching Rocket League®: DOTNET_BUNDLE_EXTRACT_BASE_DIR= HEROIC_APP_NAME=Sugar HEROIC_APP_RUNNER=legendary HEROIC_APP_SOURCE=epic LD_PRELOAD= WINEPREFIX="/home/richard/Games/Heroic/Prefixes/Rocket League" WINEDLLOVERRIDES=winemenubuilder.exe=d WINE_FULLSCREEN_FSR=0 WINEESYNC=1 WINEFSYNC=1 ORIG_LD_LIBRARY_PATH= XDG_CONFIG_HOME=/home/richard/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Sugar --wine /usr/bin/wine --language en
(13:47:09) INFO:    [Backend]:          Stopped Discord Rich Presence
(13:47:09) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(13:47:09) INFO:    [Frontend]:         Refreshing legendary Library
(13:47:09) INFO:    [Legendary]:        Refreshing library...
(13:47:09) INFO:    [Legendary]:        Refreshing Epic Games...
(13:47:09) INFO:    [Legendary]:        Game list updated, got 11 games & DLCs
(13:47:09) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/richard/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(16:08:09) INFO:    [Backend]:          Launching Rocket League® (Sugar)
(16:08:09) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(16:08:09) INFO:    [Backend]:          Stopping Power Saver Blocker
(16:08:09) INFO:    [Backend]:          Started Discord Rich Presence
(16:08:09) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(16:08:09) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(16:08:09) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(16:08:09) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-8.1!
Missing undefined and/or undefined!
Falling back to system libraries!
(16:08:09) DEBUG:   [Backend]:          Running Wine command: wineboot --init
(16:08:13) INFO:    [DXVKInstaller]:    installing dxvk on... /home/richard/Games/Heroic/Prefixes/Rocket League
(16:08:13) INFO:    [DXVKInstaller]:    dxvk already installed!
(16:08:13) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-8.1!
Missing undefined and/or undefined!
Falling back to system libraries!
(16:08:13) INFO:    [Legendary]:        Launching Rocket League®: DOTNET_BUNDLE_EXTRACT_BASE_DIR= HEROIC_APP_NAME=Sugar HEROIC_APP_RUNNER=legendary HEROIC_APP_SOURCE=epic LD_PRELOAD= WINEPREFIX="/home/richard/Games/Heroic/Prefixes/Rocket League" WINEDLLOVERRIDES=winemenubuilder.exe=d WINE_FULLSCREEN_FSR=0 WINEESYNC=1 WINEFSYNC=1 ORIG_LD_LIBRARY_PATH= XDG_CONFIG_HOME=/home/richard/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Sugar --wine /usr/bin/wine --language en
(18:07:47) INFO:    [Backend]:          Stopped Discord Rich Presence
(18:07:47) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(18:07:47) INFO:    [Frontend]:         Refreshing legendary Library
(18:07:47) INFO:    [Legendary]:        Refreshing library...
(18:07:47) INFO:    [Legendary]:        Refreshing Epic Games...
(18:07:47) INFO:    [Legendary]:        Game list updated, got 11 games & DLCs
(18:07:47) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/richard/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(22:45:33) INFO:    [Backend]:          Launching Rocket League® (Sugar)
(22:45:33) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(22:45:33) INFO:    [Backend]:          Stopping Power Saver Blocker
(22:45:33) INFO:    [Backend]:          Started Discord Rich Presence
(22:45:33) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(22:45:33) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(22:45:33) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(22:45:33) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-8.1!
Missing undefined and/or undefined!
Falling back to system libraries!
(22:45:33) DEBUG:   [Backend]:          Running Wine command: wineboot --init
(22:45:36) INFO:    [DXVKInstaller]:    installing dxvk on... /home/richard/Games/Heroic/Prefixes/Rocket League
(22:45:36) INFO:    [DXVKInstaller]:    dxvk already installed!
(22:45:36) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-8.1!
Missing undefined and/or undefined!
Falling back to system libraries!
(22:45:36) INFO:    [Legendary]:        Launching Rocket League®: DOTNET_BUNDLE_EXTRACT_BASE_DIR= HEROIC_APP_NAME=Sugar HEROIC_APP_RUNNER=legendary HEROIC_APP_SOURCE=epic LD_PRELOAD= WINEPREFIX="/home/richard/Games/Heroic/Prefixes/Rocket League" WINEDLLOVERRIDES=winemenubuilder.exe=d WINE_FULLSCREEN_FSR=0 WINEESYNC=1 WINEFSYNC=1 ORIG_LD_LIBRARY_PATH= XDG_CONFIG_HOME=/home/richard/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Sugar --wine /usr/bin/wine --language en
(23:20:06) INFO:    [Backend]:          Stopped Discord Rich Presence
(23:20:06) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(23:20:06) INFO:    [Frontend]:         Refreshing legendary Library
(23:20:06) INFO:    [Legendary]:        Refreshing library...
(23:20:06) INFO:    [Legendary]:        Refreshing Epic Games...
(23:20:06) INFO:    [Legendary]:        Game list updated, got 11 games & DLCs
(23:20:07) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/richard/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(16:53:06) INFO:    [Backend]:          Launching Rocket League® (Sugar)
(16:53:06) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(16:53:06) INFO:    [Backend]:          Stopping Power Saver Blocker
(16:53:06) INFO:    [Backend]:          Started Discord Rich Presence
(16:53:06) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(16:53:06) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(16:53:06) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(16:53:06) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-8.1!
Missing undefined and/or undefined!
Falling back to system libraries!
(16:53:06) DEBUG:   [Backend]:          Running Wine command: wineboot --init
(16:53:10) INFO:    [DXVKInstaller]:    installing dxvk on... /home/richard/Games/Heroic/Prefixes/Rocket League
(16:53:10) INFO:    [DXVKInstaller]:    dxvk already installed!
(16:53:10) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-8.1!
Missing undefined and/or undefined!
Falling back to system libraries!
(16:53:10) INFO:    [Legendary]:        Launching Rocket League®: DOTNET_BUNDLE_EXTRACT_BASE_DIR= HEROIC_APP_NAME=Sugar HEROIC_APP_RUNNER=legendary HEROIC_APP_SOURCE=epic LD_PRELOAD= WINEPREFIX="/home/richard/Games/Heroic/Prefixes/Rocket League" WINEDLLOVERRIDES=winemenubuilder.exe=d WINE_FULLSCREEN_FSR=0 WINEESYNC=1 WINEFSYNC=1 ORIG_LD_LIBRARY_PATH= XDG_CONFIG_HOME=/home/richard/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Sugar --wine /usr/bin/wine --language en
(17:42:21) INFO:    [Backend]:          Stopped Discord Rich Presence
(17:42:21) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(17:42:21) INFO:    [Frontend]:         Refreshing legendary Library
(17:42:21) INFO:    [Legendary]:        Refreshing library...
(17:42:21) INFO:    [Legendary]:        Refreshing Epic Games...
(17:42:21) INFO:    [Legendary]:        Game list updated, got 11 games & DLCs
(17:42:21) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/richard/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(12:27:44) INFO:    [Backend]:          Launching Rocket League® (Sugar)
(12:27:44) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(12:27:44) INFO:    [Backend]:          Stopping Power Saver Blocker
(12:27:44) INFO:    [Backend]:          Started Discord Rich Presence
(12:27:44) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(12:27:44) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(12:27:44) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(12:27:44) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-8.1!
Missing undefined and/or undefined!
Falling back to system libraries!
(12:27:44) DEBUG:   [Backend]:          Running Wine command: wineboot --init
(12:27:48) INFO:    [DXVKInstaller]:    installing dxvk on... /home/richard/Games/Heroic/Prefixes/Rocket League
(12:27:48) INFO:    [DXVKInstaller]:    dxvk already installed!
(12:27:48) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-8.1!
Missing undefined and/or undefined!
Falling back to system libraries!
(12:27:48) INFO:    [Legendary]:        Launching Rocket League®: DOTNET_BUNDLE_EXTRACT_BASE_DIR= HEROIC_APP_NAME=Sugar HEROIC_APP_RUNNER=legendary HEROIC_APP_SOURCE=epic LD_PRELOAD= WINEPREFIX="/home/richard/Games/Heroic/Prefixes/Rocket League" WINEDLLOVERRIDES=winemenubuilder.exe=d WINE_FULLSCREEN_FSR=0 WINEESYNC=1 WINEFSYNC=1 ORIG_LD_LIBRARY_PATH= XDG_CONFIG_HOME=/home/richard/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Sugar --wine /usr/bin/wine --language en
(13:57:12) INFO:    [Backend]:          Stopped Discord Rich Presence
(13:57:12) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(13:57:12) INFO:    [Frontend]:         Refreshing legendary Library
(13:57:12) INFO:    [Legendary]:        Refreshing library...
(13:57:12) INFO:    [Legendary]:        Refreshing Epic Games...
(13:57:12) INFO:    [Legendary]:        Game list updated, got 11 games & DLCs
(13:57:12) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/richard/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(16:47:37) INFO:    [Backend]:          Launching Rocket League® (Sugar)
(16:47:37) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(16:47:37) INFO:    [Backend]:          Stopping Power Saver Blocker
(16:47:37) INFO:    [Backend]:          Started Discord Rich Presence
(16:47:37) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(16:47:37) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(16:47:37) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(16:47:37) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-8.1!
Missing undefined and/or undefined!
Falling back to system libraries!
(16:47:37) DEBUG:   [Backend]:          Running Wine command: wineboot --init
(16:47:41) INFO:    [DXVKInstaller]:    installing dxvk on... /home/richard/Games/Heroic/Prefixes/Rocket League
(16:47:41) INFO:    [DXVKInstaller]:    dxvk already installed!
(16:47:41) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-8.1!
Missing undefined and/or undefined!
Falling back to system libraries!
(16:47:41) INFO:    [Legendary]:        Launching Rocket League®: DOTNET_BUNDLE_EXTRACT_BASE_DIR= HEROIC_APP_NAME=Sugar HEROIC_APP_RUNNER=legendary HEROIC_APP_SOURCE=epic LD_PRELOAD= WINEPREFIX="/home/richard/Games/Heroic/Prefixes/Rocket League" WINEDLLOVERRIDES=winemenubuilder.exe=d WINE_FULLSCREEN_FSR=0 WINEESYNC=1 WINEFSYNC=1 ORIG_LD_LIBRARY_PATH= XDG_CONFIG_HOME=/home/richard/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Sugar --wine /usr/bin/wine --language en
(17:04:31) INFO:    [Backend]:          Stopped Discord Rich Presence
(17:04:31) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(17:04:31) INFO:    [Frontend]:         Refreshing legendary Library
(17:04:31) INFO:    [Legendary]:        Refreshing library...
(17:04:31) INFO:    [Legendary]:        Refreshing Epic Games...
(17:04:31) INFO:    [Legendary]:        Game list updated, got 11 games & DLCs
(17:04:31) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/richard/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(17:37:11) INFO:    [Backend]:          Launching Rocket League® (Sugar)
(17:37:11) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(17:37:11) INFO:    [Backend]:          Stopping Power Saver Blocker
(17:37:11) INFO:    [Backend]:          Started Discord Rich Presence
(17:37:11) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(17:37:11) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(17:37:11) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(17:37:11) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-8.1!
Missing undefined and/or undefined!
Falling back to system libraries!
(17:37:11) DEBUG:   [Backend]:          Running Wine command: wineboot --init
(17:37:14) INFO:    [DXVKInstaller]:    installing dxvk on... /home/richard/Games/Heroic/Prefixes/Rocket League
(17:37:14) INFO:    [DXVKInstaller]:    dxvk already installed!
(17:37:14) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-8.1!
Missing undefined and/or undefined!
Falling back to system libraries!
(17:37:14) INFO:    [Legendary]:        Launching Rocket League®: DOTNET_BUNDLE_EXTRACT_BASE_DIR= HEROIC_APP_NAME=Sugar HEROIC_APP_RUNNER=legendary HEROIC_APP_SOURCE=epic LD_PRELOAD= WINEPREFIX="/home/richard/Games/Heroic/Prefixes/Rocket League" WINEDLLOVERRIDES=winemenubuilder.exe=d WINE_FULLSCREEN_FSR=0 WINEESYNC=1 WINEFSYNC=1 ORIG_LD_LIBRARY_PATH= XDG_CONFIG_HOME=/home/richard/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Sugar --wine /usr/bin/wine --language en
(17:45:41) INFO:    [Backend]:          Stopped Discord Rich Presence
(17:45:41) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(17:45:41) INFO:    [Frontend]:         Refreshing legendary Library
(17:45:41) INFO:    [Legendary]:        Refreshing library...
(17:45:41) INFO:    [Legendary]:        Refreshing Epic Games...
(17:45:41) INFO:    [Legendary]:        Game list updated, got 11 games & DLCs
(17:45:42) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/richard/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(21:15:07) INFO:    [Backend]:          Launching Rocket League® (Sugar)
(21:15:07) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(21:15:07) INFO:    [Backend]:          Stopping Power Saver Blocker
(21:15:07) INFO:    [Backend]:          Started Discord Rich Presence
(21:15:07) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(21:15:07) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(21:15:07) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(21:15:07) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-8.1!
Missing undefined and/or undefined!
Falling back to system libraries!
(21:15:07) DEBUG:   [Backend]:          Running Wine command: wineboot --init
(21:15:11) INFO:    [DXVKInstaller]:    installing dxvk on... /home/richard/Games/Heroic/Prefixes/Rocket League
(21:15:11) INFO:    [DXVKInstaller]:    dxvk already installed!
(21:15:11) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-8.1!
Missing undefined and/or undefined!
Falling back to system libraries!
(21:15:11) INFO:    [Legendary]:        Launching Rocket League®: DOTNET_BUNDLE_EXTRACT_BASE_DIR= HEROIC_APP_NAME=Sugar HEROIC_APP_RUNNER=legendary HEROIC_APP_SOURCE=epic LD_PRELOAD= WINEPREFIX="/home/richard/Games/Heroic/Prefixes/Rocket League" WINEDLLOVERRIDES=winemenubuilder.exe=d WINE_FULLSCREEN_FSR=0 WINEESYNC=1 WINEFSYNC=1 ORIG_LD_LIBRARY_PATH= XDG_CONFIG_HOME=/home/richard/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Sugar --wine /usr/bin/wine --language en
(21:46:25) INFO:    [Backend]:          Stopped Discord Rich Presence
(21:46:25) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(21:46:25) INFO:    [Frontend]:         Refreshing legendary Library
(21:46:25) INFO:    [Legendary]:        Refreshing library...
(21:46:25) INFO:    [Legendary]:        Refreshing Epic Games...
(21:46:25) INFO:    [Legendary]:        Game list updated, got 11 games & DLCs
(21:46:25) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/richard/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(21:53:52) INFO:    [Backend]:          Launching Rocket League® (Sugar)
(21:53:52) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(21:53:52) INFO:    [Backend]:          Stopping Power Saver Blocker
(21:53:52) INFO:    [Backend]:          Started Discord Rich Presence
(21:53:52) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(21:53:52) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(21:53:52) INFO:    [Backend]:          Checking if wine version exists: Wine Default - wine-8.1
(21:53:52) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-8.1!
Missing undefined and/or undefined!
Falling back to system libraries!
(21:53:52) DEBUG:   [Backend]:          Running Wine command: wineboot --init
(21:53:56) INFO:    [DXVKInstaller]:    installing dxvk on... /home/richard/Games/Heroic/Prefixes/Rocket League
(21:53:56) INFO:    [DXVKInstaller]:    dxvk already installed!
(21:53:56) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-8.1!
Missing undefined and/or undefined!
Falling back to system libraries!
(21:53:56) INFO:    [Legendary]:        Launching Rocket League®: DOTNET_BUNDLE_EXTRACT_BASE_DIR= HEROIC_APP_NAME=Sugar HEROIC_APP_RUNNER=legendary HEROIC_APP_SOURCE=epic LD_PRELOAD= WINEPREFIX="/home/richard/Games/Heroic/Prefixes/Rocket League" WINEDLLOVERRIDES=winemenubuilder.exe=d WINE_FULLSCREEN_FSR=0 WINEESYNC=1 WINEFSYNC=1 ORIG_LD_LIBRARY_PATH= XDG_CONFIG_HOME=/home/richard/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Sugar --wine /usr/bin/wine --language en
```

### Steps to reproduce

1. Turn on Discord Rich Presence
2. Start Discord
3. Start Rocket League

### Expected behavior

User list shows:

**MyUsername**
Playing Rocket League

### Screenshots

_No response_

### Heroic Version

Latest Stable

### System Information

Kernel: 6.1.55-1-MANJARO 

wine-8.17
Discord Stable 240237 (a1ba594)

CPU: 16x AMD Ryzen 7 5800X 8-Core Processor
Memory: 67.34 GB (used: 40.53 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation GA104 [GeForce RTX 3060]
    IDs: D=2487 V=10de SD=4074 SV=1458
    Driver: nvidia v: 535.113.01
OS: Manjaro Linux 6.1.55-1-MANJARO (linux)
Desktop: KDE Plasma v: 5.27.8

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.9.2 Boa Hancock
  Legendary: 0.20.32 Dark Energy (hotfix #6)
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by imLinguin**
Made a Discord RPC a bit nicer, and added a new field in GameInfo struct for providing best images for icons.
So it turns out we can give the URL instead of the key too...

Closes #3179
Closes #2869

obraz

obraz

obraz

obraz

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

File: src/backend/storeManagers/gog/library.ts [hunk 1]
```diff
@@ -948,6 +948,14 @@ export async function gogToUnifiedInfo(
     ?.replace('{formatter}', '')
     .replace('{ext}', 'jpg')
 
+  const icon =
+    info.game?.square_icon.url_format
+      ?.replace('{formatter}', '')
+      .replace('{ext}', 'jpg') ||
+    info.game?.icon?.url_format
+      ?.replace('{formatter}', '')
+      .replace('{ext}', 'jpg')
```
Comment (CommandMC) [inline src/backend/storeManagers/gog/library.ts:957]: Nitpicking, but would
```suggestion
  const icon = (info.game.square_icon.url_format || info.game.icon?.url_format)
    ?.replace('{formatter}', '')
    .replace('{ext}', 'jpg')
```
work?

Comment (imLinguin) [reply src/backend/storeManagers/gog/library.ts]: good point

**Comment by imLinguin** [comment]
Closes #3179 
Closes #2869

**Review by Etaash-mathamsetty — APPROVED** [review]
lgtm

**Review by CommandMC — APPROVED** [review]
