### PR TITLE
[Fix] Small fixes

### LINKED ISSUE #2296: Mac default wine settings are broken
### Describe the bug

the last update (2.5.2) has changed the default wine settings on Mac : while it still shows Crossover as selected, it asks for a wine prefix file path (which should be replaced by the crossover prefix which is a string and not a file path), and shows an error alert when trying to launch a game

Switching the "Crossover version" to Wine 7 stable (which I had installed) and back to crossover fixes the issue and replaces the wine prefix field with the crossover prefix (with its previous correct setting) and allowed me to play games again

### Add logs

```text
no log available sorry once I fixed the issue I couldn't reproduce it
```

### Steps to reproduce

1. on macOS, install a windows game from EGS and launch it
2. error, game won't launch
3. look in default game settings and notice that the default Crossover prefix has been replaced by Wine prefix

### Expected behavior

default crossover prefix shouldn't be switched to wine prefix

### Screenshots

_No response_

### Heroic Version

Latest Stable

### System Information

- macOS Ventura 13.1

### Additional information

_No response_

### LINKED ISSUE #2347: [UX] No game status indication in library when in gamepad/controller layout
### Describe the bug

When using a controller to navigate Heroic, if you start a game directly from the Library with the shortcut button, there's is no indication that anything is happening (neither starting, crashed, stopped, nothing), and there's no way to stop the game either.

### Add logs

```text
Nothing relevant on logs, it's a UI/UX issue.
```

### Steps to reproduce

1. Start moving through the library with a controller
2. Press the shortcut button to launch a game from the library (Y button on Xbox controllers)
3. It's not clear what is happening until the game actually starts (and if it failed there's no way to know)

### Expected behavior

Something should change visually to indicate that the game is starting.

Maybe a way to force stop a game is not needed.

### Screenshots

_No response_

### Heroic Version

main branch from GitHub

### System Information

Not relevant

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by flavioislima**
- Fix Sideloaded games being added to steam after being edited.
- Fix auto shortcuts not working when importing games.
- Fix showing sync save settings on native Linux games.
- Fix #2296
- Fix #2347 

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

File: src/frontend/screens/Settings/sections/GamesSettings/index.tsx [hunk 1]
```diff
@@ -154,7 +154,7 @@ export default function GamesSettings({ useDetails = true }: Props) {
         <PreferedLanguage />
       </Collapsible>
 
-      {hasCloudSaves && (
+      {hasCloudSaves && !isLinuxNative && (
```
Comment (redromnon) [inline src/frontend/screens/Settings/sections/GamesSettings/index.tsx:157]: Fixes Cloud Save Syncing being displayed for GOG Linux games because of missing `!isLinuxNative` check

**Review by Nocccer — APPROVED** [review]
LGTM
