### PR TITLE
[Fix] Not able to enable Steam Runtime

### LINKED ISSUE #1107: Unable to check the steam runtime box (even after setting the path)
### Describe the bug

I can't check the "steam runtime" checkbox in a games setting tab.

### Add logs

Got none

### Steps to reproduce

1) Install Baldur's Gate 2: Enhanced Edition from GOG
2) Even though its a Linux game. I can't start it.
3) I was asked to use the steam runtime (heroic games specific settings) -> checkbox can't be set
3) I was asked to add the steam path to the heroic flatpak -.> I used flatseal (see below) -> still can't check the setbox

### Expected behavior

Checking the game specific checkbox steam runtime in heroic-

### Screenshots

Screenshot_20220313_102230

### System Information

- OS [e. g. "Ubuntu"]: Ubuntu 20.4
- Heroic Version [e. g. 2.1.1]: 2.2.6 (flatpak)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by imLinguin**
This is a easy fix.
Closes #1107 

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

File: src/screens/Settings/components/OtherSettings/index.tsx [hunk 1]
```diff
@@ -211,14 +211,14 @@ export default function OtherSettings({
           </span>
           {isLinuxNative && (
             <span className="setting">
-              <span className={classNames('toggleWrapper', { isRTL: isRTL })}>
+              <label className={classNames('toggleWrapper', { isRTL: isRTL })}>
                 <ToggleSwitch
```
Comment (flavioislima) [inline src/screens/Settings/components/OtherSettings/index.tsx:215]: Why changing from a span to a label fixes it?
Also, would be good to check the logic on the backend as well. To be sure it's using the right path.

Comment (flavioislima) [reply src/screens/Settings/components/OtherSettings/index.tsx:215]: I see, ok then. 👍🏽

**Review by flavioislima — APPROVED** [review]
