### PR TITLE
Fix virtual keyboard keypress

### LINKED ISSUE #1510: [SteamDeck] Non-functional on screen keyboard
### Describe the bug

If I open Heroic Games Launcher on my Steam Deck a non functional on screen keyboard (OSK) appears if I navigate to the search box using the gamepad. The keys of this OSK don't work, with no text appearing when they are selected. 

### Add logs

(19:34:40) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(19:34:41) INFO:    [Legendary]:       Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(19:34:41) INFO:    [Gog]:             GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(19:34:41) INFO:    [Backend]:         

Heroic Version: 2.3.9 Brook
Legendary Version:  0.20.26 Dark Energy
OS: Freedesktop.org KERNEL: 5.13.0-valve15-1-neptune-02197-gf6ec7ad3762a ARCH: x64
CPU: AMD Custom APU 0405 @1.81 GOVERNOR: schedutil
RAM: Total: 14.49 GiB Available: 11.31 GiB
GRAPHICS: GPU0: Device 163f VRAM: 512MB DRIVER:  
PROTOCOL: x11

(19:34:41) INFO:    [Gog]:             Getting data about the user
(19:34:41) WARNING: [Backend]:         Failed to register protocol with OS.
(19:34:41) INFO:    [Gog]:             Saved user data to config
(19:34:42) INFO:    [Frontend]:        Refreshing Library
(19:34:42) INFO:    [Legendary]:       Refreshing library...
(19:34:42) INFO:    [Legendary]:       Refreshing Epic Games...
(19:34:42) INFO:    [Gog]:             Getting GOG library
(19:34:43) INFO:    [Gog]:             Number of library pages: 2
(19:34:43) INFO:    [Gog]:             Getting data for page 2
(19:34:43) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(19:34:43) INFO:    [Gog]:             Saved games data
(19:34:44) INFO:    [Backend]:         Downloaded Winetricks
(19:34:45) INFO:    [Legendary]:       Updating game list
(19:34:45) INFO:    [Legendary]:       Game List Updated
(19:34:45) INFO:    [Legendary]:       Checking for game updates: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(19:34:45) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(19:34:46) INFO:    [Legendary]:       Found 0 game(s) to update
(19:34:46) INFO:    [Gog]:             Found 0 game(s) to update

### Steps to reproduce

1. Open Heroic on a steam deck in game mode
2. Navigate to the search box using the gamepad controls and press gamepad "A" button
3. Observe apperance of non-functional On-screen Keyboard

### Expected behavior

Selecting the search box using the gamepad controls on a Steam Deck should either open the native Steam Deck On Screen Keyboard (usually accessed via "Steam key + X") or do nothing. 

### System Information

- OS SteamOS Holo
- Heroic Version 2.3.9 (flatpak)

### Additional information

_No response_

### LINKED ISSUE #1607: Can't select any keys with onscreen keyboard
### Describe the bug

Using my xbox and dualsense controllers, the onscreen keyboard does not work (it opens but I cannot type anything no matter how hard I try)

### Add logs

```
(17:00:42) INFO:    [Legendary]:       Running command: /tmp/.mount_Heroic7pT8I9/resources/app.asar.unpacked/build/bin/linux/legendary --version
(17:00:42) INFO:    [Legendary]:       Legendary location: /tmp/.mount_Heroic7pT8I9/resources/app.asar.unpacked/build/bin/linux/legendary
(17:00:42) INFO:    [Gog]:             GOGDL location: /tmp/.mount_Heroic7pT8I9/resources/app.asar.unpacked/build/bin/linux/gogdl
(17:00:42) INFO:    [Backend]:         

Heroic Version: 2.4.0-beta.2 Caesar Clown
Legendary Version:  0.20.27 Dark Energy (hotfix)
OS: Arch KERNEL: 5.18.12-arch1-1 ARCH: x64
CPU: AMD Ryzen 7 4700U with Radeon Graphics @2 GOVERNOR: schedutil
RAM: Total: 15 GiB Available: 8.08 GiB
GRAPHICS: GPU0: gfx90c:xnack- VRAM: 512MB DRIVER:  
PROTOCOL: wayland

(17:00:42) INFO:    [Gog]:             Getting data about the user
(17:00:43) WARNING: [Backend]:         Protocol already registered.
(17:00:43) INFO:    [Backend]:         AreWeAntiCheatYet data downloaded
(17:00:43) INFO:    [Gog]:             Saved user data to config
(17:00:44) INFO:    [Frontend]:        Refreshing Library
(17:00:44) INFO:    [Legendary]:       Refreshing library...
(17:00:44) INFO:    [Legendary]:       Refreshing Epic Games...
(17:00:44) INFO:    [Gog]:             Getting GOG library
(17:00:44) INFO:    [Legendary]:       Running command: /tmp/.mount_Heroic7pT8I9/resources/app.asar.unpacked/build/bin/linux/legendary list
(17:00:44) INFO:    [Gog]:             Number of library pages: 1
(17:00:45) INFO:    [Gog]:             Saved games data
(17:00:45) INFO:    [Legendary]:       Updating game list
(17:00:45) INFO:    [Legendary]:       Game List Updated
(17:00:45) INFO:    [Legendary]:       Checking for game updates.
(17:00:45) INFO:    [Legendary]:       Running command: /tmp/.mount_Heroic7pT8I9/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(17:00:46) INFO:    [Backend]:         Downloaded Winetricks
(17:00:46) INFO:    [Legendary]:       Found 0 game(s) to update
(17:00:46) INFO:    [Gog]:             Found 0 game(s) to update
(17:02:06) INFO:    [Legendary]:       Running command: /tmp/.mount_Heroic7pT8I9/resources/app.asar.unpacked/build/bin/linux/legendary --version
(17:02:06) INFO:    [Gog]:             Running command: /tmp/.mount_Heroic7pT8I9/resources/app.asar.unpacked/build/bin/linux/gogdl --version
(17:02:06) WARNING: [Legendary]:       EOS Overlay is not installed in default location, permission issues might arise
(17:02:06) WARNING: [Legendary]:       EOS Overlay is not installed in default location, permission issues might arise
(17:02:06) WARNING: [Legendary]:       EOS Overlay is not installed in default location, permission issues might arise

```

### Steps to reproduce

1. select search box with a controller
2. cannot type with on screen keyboard

### Expected behavior

the onscreen keyboard should work correctly

### Screenshots

_No response_

### System Information

- OS Arch linux
- Heroic Version latest from PR #1595 (also broken on heroic 2.3.10)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by arielj**
This PR fixes the virtual keyboard ketpress handler that had the wrong selector to write in the search box.

This fixes #1607 and should also fix #1510 

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

File: src/helpers/virtualKeyboard.ts [hunk 1]
```diff
@@ -8,7 +8,7 @@ function currentElement() {
 }
 
 function searchInput() {
-  return document.querySelector('.searchInput') as HTMLInputElement
+  return document.querySelector('#search') as HTMLInputElement
```
Comment (flavioislima) [inline src/helpers/virtualKeyboard.ts:11]: Maybe add a comment here as well so we don't change this in the future and break it again.

**Review by flavioislima — APPROVED** [review]

**Comment by flavioislima** [comment]
Tested with the dualsense and its working fine now.
