### PR TITLE
fix: change user-agent at runtime

### LINKED ISSUE #4223: Error login into Epic Games account
### Describe the bug

In Heroic games launcher, Trying to login to Epic Games account after confirming captcha and 2 factor code redirect to an unknown error url: https://www.unrealengine.com/id/error?errorTitleCode=error.500.title&errorCode=error.invalidClient.wrongParameters

image

This also happens from any web browser in any device trying to login via: https://legendary.gl/epiclogin

### Add logs

```text
(13:56:43) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary
(13:56:43) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl
(13:56:43) INFO:    [Connection]:       Connectivity: check-online
(13:56:43) INFO:    [Connection]:       Pinging external endpoints
(13:56:43) INFO:    [Gog]:              Checking for existing gog manifests
(13:56:43) INFO:    [Nile]:             Refreshing library...
(13:56:43) INFO:    [Nile]:             Refreshing Amazon Games...
(13:56:43) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile library sync
(13:56:43) INFO:    [Nile]:             Game list updated, got 238 games
(13:56:43) WARNING: [Backend]:          Failed to register protocol with OS.
(13:56:43) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary --version
(13:56:43) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(13:56:43) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile --version
(13:56:43) INFO:    [Connection]:       Connectivity: online
(13:56:43) INFO:    [Backend]:          User Not Found, removing it from Store
(13:56:43) INFO:    [Gog]:              Checking if login is valid
(13:56:43) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(13:56:43) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(13:56:43) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(13:56:44) INFO:    [Nile]:             Saved user data to config file
(13:56:44) INFO:    [Frontend]:         Refreshing undefined Library
(13:56:44) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(13:56:44) INFO:    [Legendary]:        Refreshing library...
(13:56:44) INFO:    [Nile]:             Refreshing library...
(13:56:44) INFO:    [Nile]:             Refreshing Amazon Games...
(13:56:44) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile library sync
(13:56:44) INFO:    [Nile]:             Game list updated, got 238 games
(13:56:44) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(13:56:44) INFO:    [Backend]:          Frontend Ready
(13:56:44) INFO:    [Backend]:          
System Information:
CPU: 8x AMD Custom APU 0932
Memory: 15.53 GB (used: 3.77 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Sephiroth [AMD Custom GPU 0405]
    IDs: D=1435 V=1002 SD=0123 SV=1002
    Driver: amdgpu
OS: SteamOS 3.6.20 holo (linux)

The current system is a Steam Deck (model: OLED) in desktop mode
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.15.2 Emeth
  Legendary: 0.20.36 Urban Flight (Heroic)
  gogdl: 1.1.2
  comet: comet 0.1.2

  Nile: 1.1.2 Will A. Zeppeli

(13:56:44) INFO:    [Gog]:              Getting GOG library
(13:56:44) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(13:56:44) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(13:56:44) INFO:    [Gog]:              GOG presence set
(13:56:44) INFO:    [Backend]:          Checking for current version changelog
(13:56:44) INFO:    [Gog]:              Saved username to config file
(13:56:45) INFO:    [Gog]:              Saved games data
(13:56:45) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(13:56:45) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(13:56:45) INFO:    [Gog]:              Found 0 game(s) to update
(13:56:45) INFO:    [Nile]:             Looking for updates...
(13:56:45) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile list-updates --json
(13:56:46) INFO:    [Winetricks]:       Downloading Winetricks
(13:56:48) INFO:    [WineDownloader]:   Updating wine versions info
(13:56:48) INFO:    [WineDownloader]:   Fetching upstream information...
(13:56:49) INFO:    [Backend]:          Starting the Download Queue
(13:56:49) INFO:    [WineDownloader]:   wine versions updated
```

### Steps to reproduce

1 - Open Heroic games Launcher and go to Manage Accounts
2 - Select Epic Games Login or Alternative Login Method
3 - Insert Epic account credentials
4 - Confirm captcha correctly
5 - Insert 2 factor code
6 - Redirects to Epic Games url Unkown Error page: Sorry, the client that sent you here did not pass the parameters needed for you to login.

### Expected behavior

Expected behaviour is to login correctly and load account games.

### Screenshots

image

### Heroic Version

Latest Stable

### System Information

- Steam Deck OS: SteamOS Holo 3.6.20 Build 20241030.1

### Additional information

Issue also reproduced in any web browser on any device

### LINKED ISSUE #4289: Heroic logged me out of Epic with no way to log back in
### Describe the bug

I tried to open one of my games from Epic games from Heroic through Steam, and it didn't open, so I opened Heroic to see that I have been logged out. Upon pressing Epic Games login it gives me this error:

  "errorCode": "errors.com.epicgames.oauth.corrective_action_required",
  "message": "Corrective action is required to continue.",
  "metadata": {
    "correctiveAction": "PRIVACY_POLICY_ACCEPTANCE",
    "continuation": "ed96f9586c3d4b7bb5267415b5f7338b"
  },
  "correlationId": "4071d020-d52d-11ef-9b44-efa2b9da6785"
}

(Trying to log through the alternative method yields the exact same result)

### Add logs

```text
(01:41:35) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary

(01:41:35) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl

(01:41:35) INFO:    [Connection]:       Connectivity: check-online

(01:41:35) INFO:    [Connection]:       Pinging external endpoints

(01:41:35) INFO:    [Gog]:              Checking for existing gog manifests

(01:41:35) WARNING: [Backend]:          Failed to register protocol with OS.

(01:41:35) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/pocket/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary --version

(01:41:35) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/pocket/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/pocket/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version

(01:41:36) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/pocket/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile --version

(01:41:36) INFO:    [Connection]:       Connectivity: online

(01:41:36) INFO:    [Backend]:          User Not Found, removing it from Store

(01:41:36) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present

(01:41:36) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/pocket/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/pocket/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth

(01:41:36) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded

(01:41:36) INFO:    [Backend]:          

System Information:

CPU: 8x Intel(R) Core(TM) i3-10105F CPU @ 3.70GHz

Memory: 16.62 GB (used: 3.72 GB)

GPUs:

  GPU 0:

    Name: NVIDIA Corporation TU116 [GeForce GTX 1660]

    IDs: D=2184 V=10de SD=2184 SV=10de

    Driver: nvidia

OS: Fedora Linux 41 (Workstation Edition) (linux)

The current system is not a Steam Deck

We are running inside a Flatpak container

Software Versions:

  Heroic: 2.15.2 Emeth

  Legendary: 0.20.36 Urban Flight (Heroic)

  gogdl: 1.1.2

  comet: comet 0.1.2

  Nile: 1.1.2 Will A. Zeppeli

(01:41:37) INFO:    [Backend]:          Frontend Ready

(01:41:37) INFO:    [Backend]:          Checking for current version changelog

(01:41:38) INFO:    [Winetricks]:       Downloading Winetricks

(01:41:40) INFO:    [WineDownloader]:   Updating wine versions info

(01:41:40) INFO:    [WineDownloader]:   Fetching upstream information...

(01:41:40) INFO:    [WineDownloader]:   wine versions updated

(01:41:42) INFO:    [Backend]:          Starting the Download Queue
```

### Steps to reproduce

1. Log out 
2. Go to 'Log nn'
3. Click on 'Epic Games Login '

### Expected behavior

It should give me the option to login with an Epic Games account

### Screenshots

Image

### Heroic Version

Latest Stable (Flatpak)

### System Information

- OS: Fedora Workstation 41

### Additional information

_No response_

### LINKED ISSUE #4419: Cannot Login to Epic Games Store
### Describe the bug

Heroic logged me out of the Epic Games Store and then when I tried to sign in, the epic games store said I needed to provide a client ID

### Add logs

```text
[3/15/2025, 11:32:51 PM] LEGENDARY_CONFIG_PATH="/Users/username/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/arm64/darwin/legendary --version

legendary version "0.20.36", codename "Urban Flight (Heroic)"
```

### Steps to reproduce

1. Go to 'Stores'
2. Click on 'LOG IN'
3. Attempt to Sign in using Google

### Expected behavior

I just expect it to sign me in!

### Screenshots

_No response_

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: MacOS Version 15.4 Beta (24E5228e)

### Additional information

I understand my machine is running a beta software but I have not had this issue with Heroic until after I updated Heroic itself.

### LINKED ISSUE #4430: Captcha error on login screen for Epic games
### Describe the bug

Exactly the same error fixed here : CAPTCHA error #2654 with the patch #2658

### Add logs

```text
(12:33:16) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary
(12:33:16) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl
(12:33:16) INFO:    [Connection]:       Connectivity: check-online
(12:33:16) INFO:    [Connection]:       Pinging external endpoints
(12:33:16) INFO:    [Gog]:              Checking for existing gog manifests
(12:33:16) INFO:    [Nile]:             Refreshing library...
(12:33:16) INFO:    [Nile]:             Refreshing Amazon Games...
(12:33:16) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/dawolf/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile library sync
(12:33:16) INFO:    [Nile]:             Game list updated, got 1 games
(12:33:16) WARNING: [Backend]:          Failed to register protocol with OS.
(12:33:16) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/dawolf/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary --version
(12:33:16) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/dawolf/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/dawolf/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(12:33:16) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/dawolf/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile --version
(12:33:16) INFO:    [Nile]:             Saved user data to config file
(12:33:16) INFO:    [Connection]:       Connectivity: online
(12:33:16) INFO:    [Backend]:          User Not Found, removing it from Store
(12:33:16) INFO:    [Gog]:              Checking if login is valid
(12:33:16) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/dawolf/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/dawolf/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(12:33:16) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/dawolf/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/dawolf/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(12:33:16) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/dawolf/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/dawolf/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(12:33:16) INFO:    [Frontend]:         Refreshing undefined Library
(12:33:16) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(12:33:16) INFO:    [Legendary]:        Refreshing library...
(12:33:16) INFO:    [Nile]:             Refreshing library...
(12:33:16) INFO:    [Nile]:             Refreshing Amazon Games...
(12:33:16) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/dawolf/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile library sync
(12:33:16) INFO:    [Nile]:             Game list updated, got 1 games
(12:33:16) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/dawolf/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/dawolf/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(12:33:16) INFO:    [Backend]:          Frontend Ready
(12:33:16) INFO:    [Backend]:          
System Information:
CPU: 24x 13th Gen Intel(R) Core(TM) i7-13700KF
Memory: 33.43 GB (used: 9.38 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] RX-79XMERCB9 [SPEEDSTER MERC 310 RX 7900 XTX]
    IDs: D=744c V=1002 SD=7901 SV=1eae
    Driver: amdgpu
OS: Pop!_OS 22.04 LTS (linux)

The current system is not a Steam Deck
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.16.1 Scopper Gaban
  Legendary: 0.20.36 Urban Flight (Heroic)
  gogdl: 1.1.2
  comet: comet 0.2.0
  Nile: 1.1.2 Will A. Zeppeli

(12:33:16) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(12:33:16) INFO:    [Backend]:          Checking for current version changelog
(12:33:16) INFO:    [Gog]:              Getting GOG library
(12:33:16) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/dawolf/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/dawolf/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(12:33:17) INFO:    [Gog]:              GOG presence set
(12:33:17) INFO:    [Gog]:              Saved games data
(12:33:17) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(12:33:17) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/dawolf/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/dawolf/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(12:33:17) INFO:    [Gog]:              Saved username to config file
(12:33:17) INFO:    [Gog]:              Found 0 game(s) to update
(12:33:17) INFO:    [Nile]:             Looking for updates...
(12:33:17) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/dawolf/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile list-updates --json
(12:33:18) INFO:    [Winetricks]:       Downloading Winetricks
(12:33:21) INFO:    [WineDownloader]:   Updating wine versions info
(12:33:21) INFO:    [WineDownloader]:   Fetching upstream information...
(12:33:21) INFO:    [Backend]:          Starting the Download Queue
(12:33:22) INFO:    [WineDownloader]:   wine versions updated
(12:37:21) INFO:    [Backend]:          Checking for current version changelog
(12:37:51) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/dawolf/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary --version
(12:37:51) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/dawolf/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/dawolf/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(12:37:51) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/dawolf/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile --version
(12:38:16) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/dawolf/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/dawolf/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(12:38:17) INFO:    [Gog]:              GOG presence set
(12:43:16) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/dawolf/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/dawolf/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(12:43:17) INFO:    [Gog]:              GOG presence set
```

### Steps to reproduce

Try to login to Epic Games, answer the hCaptcha and see the error.

### Expected behavior

Log in the Epic Games Store.

### Screenshots

Image

Image

### Heroic Version

Latest Stable

### System Information

CPU: 24x 13th Gen Intel(R) Core(TM) i7-13700KF
Memory: 33.43 GB (used: 9.63 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] RX-79XMERCB9 [SPEEDSTER MERC 310 RX 7900 XTX]
    IDs: D=744c V=1002 SD=7901 SV=1eae
    Driver: amdgpu
OS: Pop!_OS 22.04 LTS (linux)

The current system is not a Steam Deck
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.16.1 Scopper Gaban
  Legendary: 0.20.36 Urban Flight (Heroic)
  gogdl: 1.1.2
  comet: comet 0.2.0
  Nile: 1.1.2 Will A. Zeppeli

### Additional information

_No response_

### LINKED ISSUE #4433: Failed to login Epic Games account
### Describe the bug

Whether chooses the first login option(Epic Games login) or the second login option(Epic Alternative login method), or chooses to open their links in browser, both can't login successfully and return the same error.

### Add logs

```text
[3/23/2025, 12:32:08 AM] LEGENDARY_CONFIG_PATH=/home/leafat/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary --version
legendary version "0.20.36", codename "Urban Flight (Heroic)"
[3/23/2025, 12:32:29 AM] LEGENDARY_CONFIG_PATH=/home/leafat/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary auth --code <redacted>
[cli] INFO: Testing existing login data if present...
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 789, in urlopen
  File "urllib3/connectionpool.py", line 490, in _make_request
  File "urllib3/connectionpool.py", line 466, in _make_request
  File "urllib3/connectionpool.py", line 1095, in _validate_conn
  File "urllib3/connection.py", line 730, in connect
  File "urllib3/connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
  File "urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
  File "urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
  File "ssl.py", line 501, in wrap_socket
  File "ssl.py", line 1074, in _create
  File "ssl.py", line 1343, in do_handshake
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 667, in send
  File "urllib3/connectionpool.py", line 843, in urlopen
  File "urllib3/util/retry.py", line 474, in increment
  File "urllib3/util/util.py", line 38, in reraise
  File "urllib3/connectionpool.py", line 789, in urlopen
  File "urllib3/connectionpool.py", line 490, in _make_request
  File "urllib3/connectionpool.py", line 466, in _make_request
  File "urllib3/connectionpool.py", line 1095, in _validate_conn
  File "urllib3/connection.py", line 730, in connect
  File "urllib3/connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
  File "urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
  File "urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
  File "ssl.py", line 501, in wrap_socket
  File "ssl.py", line 1074, in _create
  File "ssl.py", line 1343, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "legendary/cli.py", line 3224, in <module>
  File "legendary/cli.py", line 3131, in main
  File "legendary/cli.py", line 93, in auth
  File "legendary/core.py", line 274, in check_for_updates
  File "legendary/api/lgd.py", line 21, in get_version_information
  File "requests/sessions.py", line 602, in get
  File "requests/sessions.py", line 589, in request
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 682, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
[PYI-3744:ERROR] Failed to execute script 'cli' due to unhandled exception!
[3/23/2025, 12:54:10 AM] LEGENDARY_CONFIG_PATH=/home/leafat/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary auth --code <redacted>
[cli] INFO: Testing existing login data if present...
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 789, in urlopen
  File "urllib3/connectionpool.py", line 490, in _make_request
  File "urllib3/connectionpool.py", line 466, in _make_request
  File "urllib3/connectionpool.py", line 1095, in _validate_conn
  File "urllib3/connection.py", line 730, in connect
  File "urllib3/connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
  File "urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
  File "urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
  File "ssl.py", line 501, in wrap_socket
  File "ssl.py", line 1074, in _create
  File "ssl.py", line 1343, in do_handshake
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 667, in send
  File "urllib3/connectionpool.py", line 843, in urlopen
  File "urllib3/util/retry.py", line 474, in increment
  File "urllib3/util/util.py", line 38, in reraise
  File "urllib3/connectionpool.py", line 789, in urlopen
  File "urllib3/connectionpool.py", line 490, in _make_request
  File "urllib3/connectionpool.py", line 466, in _make_request
  File "urllib3/connectionpool.py", line 1095, in _validate_conn
  File "urllib3/connection.py", line 730, in connect
  File "urllib3/connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
  File "urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
  File "urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
  File "ssl.py", line 501, in wrap_socket
  File "ssl.py", line 1074, in _create
  File "ssl.py", line 1343, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "legendary/cli.py", line 3224, in <module>
  File "legendary/cli.py", line 3131, in main
  File "legendary/cli.py", line 93, in auth
  File "legendary/core.py", line 274, in check_for_updates
  File "legendary/api/lgd.py", line 21, in get_version_information
  File "requests/sessions.py", line 602, in get
  File "requests/sessions.py", line 589, in request
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 682, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
[PYI-5796:ERROR] Failed to execute script 'cli' due to unhandled exception!
[3/23/2025, 12:54:27 AM] LEGENDARY_CONFIG_PATH=/home/leafat/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary auth --code <redacted>
[cli] INFO: Testing existing login data if present...
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 789, in urlopen
  File "urllib3/connectionpool.py", line 490, in _make_request
  File "urllib3/connectionpool.py", line 466, in _make_request
  File "urllib3/connectionpool.py", line 1095, in _validate_conn
  File "urllib3/connection.py", line 730, in connect
  File "urllib3/connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
  File "urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
  File "urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
  File "ssl.py", line 501, in wrap_socket
  File "ssl.py", line 1074, in _create
  File "ssl.py", line 1343, in do_handshake
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 667, in send
  File "urllib3/connectionpool.py", line 843, in urlopen
  File "urllib3/util/retry.py", line 474, in increment
  File "urllib3/util/util.py", line 38, in reraise
  File "urllib3/connectionpool.py", line 789, in urlopen
  File "urllib3/connectionpool.py", line 490, in _make_request
  File "urllib3/connectionpool.py", line 466, in _make_request
  File "urllib3/connectionpool.py", line 1095, in _validate_conn
  File "urllib3/connection.py", line 730, in connect
  File "urllib3/connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
  File "urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
  File "urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
  File "ssl.py", line 501, in wrap_socket
  File "ssl.py", line 1074, in _create
  File "ssl.py", line 1343, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "legendary/cli.py", line 3224, in <module>
  File "legendary/cli.py", line 3131, in main
  File "legendary/cli.py", line 93, in auth
  File "legendary/core.py", line 274, in check_for_updates
  File "legendary/api/lgd.py", line 21, in get_version_information
  File "requests/sessions.py", line 602, in get
  File "requests/sessions.py", line 589, in request
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 682, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
[PYI-5837:ERROR] Failed to execute script 'cli' due to unhandled exception!
[3/23/2025, 12:54:36 AM] LEGENDARY_CONFIG_PATH=/home/leafat/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary auth --code <redacted>
[cli] INFO: Testing existing login data if present...
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 789, in urlopen
  File "urllib3/connectionpool.py", line 490, in _make_request
  File "urllib3/connectionpool.py", line 466, in _make_request
  File "urllib3/connectionpool.py", line 1095, in _validate_conn
  File "urllib3/connection.py", line 730, in connect
  File "urllib3/connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
  File "urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
  File "urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
  File "ssl.py", line 501, in wrap_socket
  File "ssl.py", line 1074, in _create
  File "ssl.py", line 1343, in do_handshake
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 667, in send
  File "urllib3/connectionpool.py", line 843, in urlopen
  File "urllib3/util/retry.py", line 474, in increment
  File "urllib3/util/util.py", line 38, in reraise
  File "urllib3/connectionpool.py", line 789, in urlopen
  File "urllib3/connectionpool.py", line 490, in _make_request
  File "urllib3/connectionpool.py", line 466, in _make_request
  File "urllib3/connectionpool.py", line 1095, in _validate_conn
  File "urllib3/connection.py", line 730, in connect
  File "urllib3/connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
  File "urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
  File "urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
  File "ssl.py", line 501, in wrap_socket
  File "ssl.py", line 1074, in _create
  File "ssl.py", line 1343, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "legendary/cli.py", line 3224, in <module>
  File "legendary/cli.py", line 3131, in main
  File "legendary/cli.py", line 93, in auth
  File "legendary/core.py", line 274, in check_for_updates
  File "legendary/api/lgd.py", line 21, in get_version_information
  File "requests/sessions.py", line 602, in get
  File "requests/sessions.py", line 589, in request
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 682, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
[PYI-6021:ERROR] Failed to execute script 'cli' due to unhandled exception!
[3/23/2025, 12:55:31 AM] LEGENDARY_CONFIG_PATH=/home/leafat/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary auth --code <redacted>
[cli] INFO: Testing existing login data if present...
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 789, in urlopen
  File "urllib3/connectionpool.py", line 490, in _make_request
  File "urllib3/connectionpool.py", line 466, in _make_request
  File "urllib3/connectionpool.py", line 1095, in _validate_conn
  File "urllib3/connection.py", line 730, in connect
  File "urllib3/connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
  File "urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
  File "urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
  File "ssl.py", line 501, in wrap_socket
  File "ssl.py", line 1074, in _create
  File "ssl.py", line 1343, in do_handshake
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 667, in send
  File "urllib3/connectionpool.py", line 843, in urlopen
  File "urllib3/util/retry.py", line 474, in increment
  File "urllib3/util/util.py", line 38, in reraise
  File "urllib3/connectionpool.py", line 789, in urlopen
  File "urllib3/connectionpool.py", line 490, in _make_request
  File "urllib3/connectionpool.py", line 466, in _make_request
  File "urllib3/connectionpool.py", line 1095, in _validate_conn
  File "urllib3/connection.py", line 730, in connect
  File "urllib3/connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
  File "urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
  File "urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
  File "ssl.py", line 501, in wrap_socket
  File "ssl.py", line 1074, in _create
  File "ssl.py", line 1343, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "legendary/cli.py", line 3224, in <module>
  File "legendary/cli.py", line 3131, in main
  File "legendary/cli.py", line 93, in auth
  File "legendary/core.py", line 274, in check_for_updates
  File "legendary/api/lgd.py", line 21, in get_version_information
  File "requests/sessions.py", line 602, in get
  File "requests/sessions.py", line 589, in request
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 682, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
[PYI-6199:ERROR] Failed to execute script 'cli' due to unhandled exception!
[3/23/2025, 12:56:14 AM] LEGENDARY_CONFIG_PATH=/home/leafat/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary auth --code <redacted>
[cli] INFO: Testing existing login data if present...
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 789, in urlopen
  File "urllib3/connectionpool.py", line 490, in _make_request
  File "urllib3/connectionpool.py", line 466, in _make_request
  File "urllib3/connectionpool.py", line 1095, in _validate_conn
  File "urllib3/connection.py", line 730, in connect
  File "urllib3/connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
  File "urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
  File "urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
  File "ssl.py", line 501, in wrap_socket
  File "ssl.py", line 1074, in _create
  File "ssl.py", line 1343, in do_handshake
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 667, in send
  File "urllib3/connectionpool.py", line 843, in urlopen
  File "urllib3/util/retry.py", line 474, in increment
  File "urllib3/util/util.py", line 38, in reraise
  File "urllib3/connectionpool.py", line 789, in urlopen
  File "urllib3/connectionpool.py", line 490, in _make_request
  File "urllib3/connectionpool.py", line 466, in _make_request
  File "urllib3/connectionpool.py", line 1095, in _validate_conn
  File "urllib3/connection.py", line 730, in connect
  File "urllib3/connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
  File "urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
  File "urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
  File "ssl.py", line 501, in wrap_socket
  File "ssl.py", line 1074, in _create
  File "ssl.py", line 1343, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "legendary/cli.py", line 3224, in <module>
  File "legendary/cli.py", line 3131, in main
  File "legendary/cli.py", line 93, in auth
  File "legendary/core.py", line 274, in check_for_updates
  File "legendary/api/lgd.py", line 21, in get_version_information
  File "requests/sessions.py", line 602, in get
  File "requests/sessions.py", line 589, in request
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 682, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
[PYI-6538:ERROR] Failed to execute script 'cli' due to unhandled exception!
[3/23/2025, 1:00:18 AM] LEGENDARY_CONFIG_PATH=/home/leafat/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary auth --code <redacted>
[cli] INFO: Testing existing login data if present...
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 789, in urlopen
  File "urllib3/connectionpool.py", line 490, in _make_request
  File "urllib3/connectionpool.py", line 466, in _make_request
  File "urllib3/connectionpool.py", line 1095, in _validate_conn
  File "urllib3/connection.py", line 730, in connect
  File "urllib3/connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
  File "urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
  File "urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
  File "ssl.py", line 501, in wrap_socket
  File "ssl.py", line 1074, in _create
  File "ssl.py", line 1343, in do_handshake
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 667, in send
  File "urllib3/connectionpool.py", line 843, in urlopen
  File "urllib3/util/retry.py", line 474, in increment
  File "urllib3/util/util.py", line 38, in reraise
  File "urllib3/connectionpool.py", line 789, in urlopen
  File "urllib3/connectionpool.py", line 490, in _make_request
  File "urllib3/connectionpool.py", line 466, in _make_request
  File "urllib3/connectionpool.py", line 1095, in _validate_conn
  File "urllib3/connection.py", line 730, in connect
  File "urllib3/connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
  File "urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
  File "urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
  File "ssl.py", line 501, in wrap_socket
  File "ssl.py", line 1074, in _create
  File "ssl.py", line 1343, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "legendary/cli.py", line 3224, in <module>
  File "legendary/cli.py", line 3131, in main
  File "legendary/cli.py", line 93, in auth
  File "legendary/core.py", line 274, in check_for_updates
  File "legendary/api/lgd.py", line 21, in get_version_information
  File "requests/sessions.py", line 602, in get
  File "requests/sessions.py", line 589, in request
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 682, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
[PYI-6765:ERROR] Failed to execute script 'cli' due to unhandled exception!
```

### Steps to reproduce

1. Go to 'login'
2. Click on 'EPIC GAMES LOGIN' or 'EPIC ALTERNATIVE LOGIN METHOD'
3. Click on 'open in browser' (Optional)
5. See error message window (return a notice page in browser at the same time if follow step 3)

### Expected behavior

login to epic games account

### Screenshots

Image

### Heroic Version

Latest Stable

### System Information

CPU: 8x Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
Memory: 8.03 GB (used: 4.02 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation GP108M [GeForce MX250]
    IDs: D=1d13 V=10de SD=39ef SV=17aa
    Driver: nvidia
  GPU 1:
    Name: Intel Corporation WhiskeyLake-U GT2 [UHD Graphics 620]
    IDs: D=3ea0 V=8086 SD=39ef SV=17aa
    Driver: i915
OS: Arch Linux 6.13.7-arch1-1 (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.16.1 Scopper Gaban
  Legendary: 0.20.36 Urban Flight (Heroic)
  gogdl: 1.1.2
  comet: comet 0.2.0
  Nile: 1.1.2 Will A. Zeppeli

### Additional information

_No response_

### LINKED ISSUE #4460: Incorrect response error when signing into Epic
### Describe the bug

When logging into Epic Games the error message "Incorrect response. Please refresh the page." appears and login is halted.

### Add logs

```text
(20:21:36) INFO:    [Legendary]:        Legendary location: C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\legendary

(20:21:36) INFO:    [Gog]:              GOGDL location: C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl

(20:21:36) INFO:    [Connection]:       Connectivity: check-online

(20:21:36) INFO:    [Connection]:       Pinging external endpoints

(20:21:36) INFO:    [Gog]:              Checking for existing gog manifests

(20:21:36) INFO:    [Nile]:             Refreshing library...

(20:21:36) INFO:    [Nile]:             Refreshing Amazon Games...

(20:21:36) INFO:    [Nile]:             Game list updated, got 40 games

(20:21:37) WARNING: [Backend]:          Protocol already registered.

(20:21:37) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\nile_config" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\nile`"" -Wait -NoNewWindow -ArgumentList "`"library`"","`"sync`""

(20:21:37) INFO:    [Connection]:       Connectivity: online

(20:21:37) INFO:    [Backend]:          User Not Found, removing it from Store

(20:21:37) INFO:    [Gog]:              Checking if login is valid

(20:21:37) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""

(20:21:37) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""

(20:21:37) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""

(20:21:37) INFO:    [Backend]:          VCRuntime is installed

(20:21:37) INFO:    [Nile]:             Saved user data to config file

(20:21:37) INFO:    [Frontend]:         Refreshing undefined Library

(20:21:37) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager

(20:21:38) INFO:    [Legendary]:        Refreshing library...

(20:21:38) INFO:    [Nile]:             Refreshing library...

(20:21:38) INFO:    [Nile]:             Refreshing Amazon Games...

(20:21:38) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\nile_config" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\nile`"" -Wait -NoNewWindow -ArgumentList "`"library`"","`"sync`""

(20:21:38) INFO:    [Nile]:             Game list updated, got 40 games

(20:21:38) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""

(20:21:38) INFO:    [Backend]:          Frontend Ready

(20:21:38) INFO:    [Backend]:          Checking for new Heroic Updates

(20:21:38) INFO:    [Backend]:          Checking for current version changelog

(20:21:38) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\legendaryConfig\legendary" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"--version`""

(20:21:38) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"--version`""

(20:21:39) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\nile_config" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\nile`"" -Wait -NoNewWindow -ArgumentList "`"--version`""

(20:21:39) INFO:    [Gog]:              Getting GOG library

(20:21:39) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""

(20:21:40) INFO:    [Gog]:              GOG presence set

(20:21:40) INFO:    [Gog]:              Saved username to config file

(20:21:41) INFO:    [Backend]:          

System Information:

CPU: 16x AMD Ryzen 7 3800XT 8-Core Processor            

Memory: 34.28 GB (used: 15.76 GB)

GPUs:

  GPU 0:

    Name: NVIDIA Corporation TU116 [GeForce GTX 1660]

    IDs: D=2184 V=10de SD=3792 SV=1462

    Driver: 572.47

OS: Microsoft Windows 11 Pro 10.0.26100 (win32)

The current system is not a Steam Deck

We are not running inside a Flatpak container

Software Versions:

  Heroic: 2.16.1 Scopper Gaban

  Legendary: 0.20.36 Urban Flight (Heroic)

  gogdl: 1.1.2

  comet: comet 0.2.0

  Nile: 1.1.2 Will A. Zeppeli

(20:21:43) INFO:    [Backend]:          Starting the Download Queue

(20:21:52) INFO:    [Gog]:              Saved games data

(20:21:52) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager

(20:21:52) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""

(20:21:54) INFO:    [Gog]:              Found 0 game(s) to update

(20:21:54) INFO:    [Nile]:             Looking for updates...

(20:21:54) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\nile_config" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\nile`"" -Wait -NoNewWindow -ArgumentList "`"list-updates`"","`"--json`""

(20:26:39) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""

(20:26:41) INFO:    [Gog]:              GOG presence set

(20:31:39) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""

(20:31:41) INFO:    [Gog]:              GOG presence set

(20:36:39) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""

(20:36:41) INFO:    [Gog]:              GOG presence set

(20:41:39) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""

(20:41:41) INFO:    [Gog]:              GOG presence set

(20:46:39) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""

(20:46:41) INFO:    [Gog]:              GOG presence set

(20:51:39) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""

(20:51:41) INFO:    [Gog]:              GOG presence set

(20:51:47) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""

(20:51:49) INFO:    [Gog]:              Getting game metadata: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"info`"","`"2121564020`"","`"--os`"","`"windows`""

(20:52:40) INFO:    [Gog]:              Got install info from cache for 2121564020 on windows platform

(20:53:09) INFO:    [Gog]:              Got install info from cache for 2121564020 on windows platform

(20:53:18) INFO:    [Gog]:              Got install info from cache for 2121564020 on windows platform

(20:53:18) INFO:    [DownloadManager]:  Flashout 3D: Enhanced Edition  was added to the download queue.

(20:53:18) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""

(20:53:18) INFO:    [Backend]:          Preventing machine to sleep

(20:53:19) INFO:    [Gog]:              Installing 2121564020: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"download`"","`"2121564020`"","`"--platform`"","`"windows`"","`"--path`"","`"E:\\GOG Games`"","`"--support`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gogdlConfig\\heroic_gogdl\\gog-support\\2121564020`"","`"--skip-dlcs`"","`"--lang`"","`"en-US`""

(20:53:19) DEBUG:   [Gog]:              Logging to file "C:\Users\Leander Tau\AppData\Roaming\heroic\GamesConfig\2121564020.log"

(20:53:21) INFO:    [Gog]:              Progress for Flashout 3D: Enhanced Edition: 0%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s

(20:53:22) INFO:    [Gog]:              Progress for Flashout 3D: Enhanced Edition: 0%/34.33MB/00:00:00 Down: 0.12MB/s / Disk: 0MB/s

(20:53:23) INFO:    [Gog]:              Progress for Flashout 3D: Enhanced Edition: 16.83%/62.21MB/00:00:12 Down: 62.33MB/s / Disk: 134.39MB/s

(20:53:24) INFO:    [Gog]:              Progress for Flashout 3D: Enhanced Edition: 24.37%/94.54MB/00:00:11 Down: 25.4MB/s / Disk: 53.92MB/s

(20:53:26) INFO:    [Gog]:              Progress for Flashout 3D: Enhanced Edition: 26.88%/165.91MB/00:00:14 Down: 6.42MB/s / Disk: 13.25MB/s

(20:53:27) INFO:    [Gog]:              Progress for Flashout 3D: Enhanced Edition: 70.1%/209.59MB/00:00:02 Down: 151.57MB/s / Disk: 337.99MB/s

(20:53:28) INFO:    [Gog]:              Progress for Flashout 3D: Enhanced Edition: 71.56%/241.56MB/00:00:02 Down: 7.79MB/s / Disk: 15.3MB/s

(20:53:29) INFO:    [Gog]:              Progress for Flashout 3D: Enhanced Edition: 84.6%/331.52MB/00:00:01 Down: 48.01MB/s / Disk: 79.44MB/s

(20:53:31) INFO:    [Gog]:              Progress for Flashout 3D: Enhanced Edition: 94.64%/356.81MB/00:00:00 Down: 23.29MB/s / Disk: 50.2MB/s

(20:53:34) INFO:    [Gog]:              Got install info from cache for 2121564020 on windows platform

(20:53:34) INFO:    [Backend]:          operation interrupted

(20:53:34) INFO:    [Gog]:              Windows os, running setup instructions on install

(20:53:34) INFO:    [Backend]:          Preventing machine to sleep

(20:53:34) INFO:    [Gog]:              Setup: Finished

(20:53:34) INFO:    [Backend]:          Adding shortcuts for Flashout 3D: Enhanced Edition

(20:53:34) INFO:    [DownloadManager]:  Finished Installation of 2121564020

(20:53:34) INFO:    [DownloadManager]:  2121564020 added to download manager finished.

(20:53:34) INFO:    [DownloadManager]:  2121564020 removed from download manager.

(20:53:34) INFO:    [Frontend]:         Refreshing gog Library

(20:53:34) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""

(20:53:34) INFO:    [Backend]:          Stopping Power Saver Blocker

(20:53:35) INFO:    [Gog]:              Getting GOG library

(20:53:35) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""

(20:53:38) INFO:    [Gog]:              Saved games data

(20:53:46) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""

(20:53:47) INFO:    [Gog]:              Getting game metadata: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"info`"","`"1370227705`"","`"--os`"","`"windows`""

(20:54:02) INFO:    [Gog]:              Got install info from cache for 1370227705 on windows platform

(20:54:02) INFO:    [DownloadManager]:  Deus Ex: Human Revolution - Director’s Cut  was added to the download queue.

(20:54:02) INFO:    [Gog]:              Updating GOG redistributables

(20:54:02) INFO:    [Gog]:              GOG REDIST:: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"redist`"","`"--ids`"","`"ISI,DirectX,MSVC2015,MSVC2015_x64,MSVC2012,MSVC2012_x64,MSVC2013_x64,MSVC2019,MSVC2008`"","`"--path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\tools\\redist\\gog`""

(20:54:02) DEBUG:   [Gog]:              Logging to file "C:\Users\Leander Tau\AppData\Roaming\heroic\GamesConfig\gog-redist.log"

(20:54:02) INFO:    [Backend]:          Preventing machine to sleep

(20:54:06) INFO:    [Gog]:              Progress for Galaxy Common Redistributables: 100%/0.00MB/00:00:00 Down: 1.96MB/s / Disk: 2.63MB/s

(20:54:07) INFO:    [DownloadManager]:  gog-redist added to download manager finished.

(20:54:07) INFO:    [DownloadManager]:  gog-redist removed from download manager.

(20:54:07) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""

(20:54:07) INFO:    [Frontend]:         Refreshing gog Library

(20:54:07) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""

(20:54:07) INFO:    [Backend]:          Stopping Power Saver Blocker

(20:54:07) INFO:    [Backend]:          operation interrupted

(20:54:07) INFO:    [Backend]:          Preventing machine to sleep

(20:54:08) INFO:    [Gog]:              Installing 1370227705: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"download`"","`"1370227705`"","`"--platform`"","`"windows`"","`"--path`"","`"E:\\GOG Games`"","`"--support`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gogdlConfig\\heroic_gogdl\\gog-support\\1370227705`"","`"--skip-dlcs`"","`"--lang`"","`"en-US`""

(20:54:08) DEBUG:   [Gog]:              Logging to file "C:\Users\Leander Tau\AppData\Roaming\heroic\GamesConfig\1370227705.log"

(20:54:08) INFO:    [Gog]:              Getting GOG library

(20:54:08) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""

(20:54:10) INFO:    [Gog]:              Saved games data

(20:54:10) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager

(20:54:10) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""

(20:54:11) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 0%/0.00MB/00:00:00 Down: 0.37MB/s / Disk: 0.73MB/s

(20:54:13) INFO:    [Gog]:              Found 0 game(s) to update

(20:54:13) INFO:    [Nile]:             Looking for updates...

(20:54:13) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\nile_config" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\nile`"" -Wait -NoNewWindow -ArgumentList "`"list-updates`"","`"--json`""

(20:54:13) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 0.33%/129.09MB/00:15:57 Down: 17.28MB/s / Disk: 33.99MB/s

(20:54:14) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 0.33%/229.85MB/00:21:02 Down: 0.49MB/s / Disk: 0MB/s

(20:54:15) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 0.44%/322.16MB/00:19:47 Down: 9.5MB/s / Disk: 19.53MB/s

(20:54:17) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 2.15%/453.00MB/00:05:16 Down: 90.02MB/s / Disk: 184.01MB/s

(20:54:18) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 2.65%/531.33MB/00:04:52 Down: 46.8MB/s / Disk: 97.92MB/s

(20:54:19) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 3.7%/647.29MB/00:04:03 Down: 63.48MB/s / Disk: 130.28MB/s

(20:54:20) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 4.3%/751.09MB/00:03:55 Down: 43.77MB/s / Disk: 89.33MB/s

(20:54:21) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 4.86%/832.48MB/00:03:51 Down: 38.96MB/s / Disk: 80.71MB/s

(20:54:23) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 5.68%/913.90MB/00:03:41 Down: 46.47MB/s / Disk: 96.92MB/s

(20:54:24) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 5.85%/986.57MB/00:03:52 Down: 13.77MB/s / Disk: 27.05MB/s

(20:54:25) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 6.57%/1077.53MB/00:03:41 Down: 57.16MB/s / Disk: 117.4MB/s

(20:54:26) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 7.23%/1135.76MB/00:03:33 Down: 55.45MB/s / Disk: 114.53MB/s

(20:54:27) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 8%/1236.02MB/00:03:25 Down: 55.6MB/s / Disk: 114.48MB/s

(20:54:29) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 8.39%/1356.36MB/00:03:28 Down: 27.96MB/s / Disk: 57.42MB/s

(20:54:30) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 8.99%/1430.81MB/00:03:22 Down: 56.97MB/s / Disk: 116.96MB/s

(20:54:31) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 9.66%/1510.55MB/00:03:16 Down: 55.07MB/s / Disk: 112.77MB/s

(20:54:32) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 10.43%/1619.12MB/00:03:10 Down: 57.89MB/s / Disk: 119.09MB/s

(20:54:33) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 11.2%/1713.64MB/00:03:06 Down: 50.43MB/s / Disk: 102.8MB/s

(20:54:34) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 11.9%/1821.99MB/00:03:02 Down: 56.99MB/s / Disk: 117.07MB/s

(20:54:35) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 12.4%/1885.90MB/00:03:01 Down: 43.78MB/s / Disk: 89.33MB/s

(20:54:36) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 13.06%/1980.17MB/00:02:58 Down: 53.77MB/s / Disk: 111.54MB/s

(20:54:38) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 13.45%/2069.11MB/00:02:59 Down: 30.36MB/s / Disk: 61.74MB/s

(20:54:39) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 13.83%/2187.56MB/00:03:02 Down: 24.32MB/s / Disk: 49.17MB/s

(20:54:40) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 14.22%/2258.31MB/00:03:04 Down: 26.94MB/s / Disk: 56.56MB/s

(20:54:41) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 14.94%/2359.49MB/00:03:01 Down: 50.71MB/s / Disk: 105.41MB/s

(20:54:43) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 14.99%/2421.42MB/00:03:07 Down: 3.81MB/s / Disk: 7.62MB/s

(20:54:44) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 15.54%/2517.50MB/00:03:04 Down: 49.86MB/s / Disk: 101.96MB/s

(20:54:45) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 16.32%/2654.17MB/00:03:02 Down: 41.46MB/s / Disk: 87.2MB/s

(20:54:46) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 16.37%/2736.51MB/00:03:07 Down: 3.72MB/s / Disk: 7.44MB/s

(20:54:47) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 16.98%/2835.48MB/00:03:04 Down: 51.41MB/s / Disk: 105.24MB/s

(20:54:49) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 17.14%/2921.36MB/00:03:08 Down: 11.51MB/s / Disk: 23.61MB/s

(20:54:50) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 17.97%/3027.71MB/00:03:02 Down: 72MB/s / Disk: 149.53MB/s

(20:54:51) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 18.36%/3089.81MB/00:03:03 Down: 27.19MB/s / Disk: 55.84MB/s

(20:54:52) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 18.36%/3172.01MB/00:03:07 Down: 0.99MB/s / Disk: 0.99MB/s

(20:54:53) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 20.29%/3224.51MB/00:02:49 Down: 168.11MB/s / Disk: 346.93MB/s

(20:54:54) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 21.12%/3298.16MB/00:02:46 Down: 60.84MB/s / Disk: 125.51MB/s

(20:54:55) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 21.89%/3417.85MB/00:02:43 Down: 48.91MB/s / Disk: 99.53MB/s

(20:54:57) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 22.74%/3529.24MB/00:02:41 Down: 43.8MB/s / Disk: 90.35MB/s

(20:54:59) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 23.35%/3602.87MB/00:02:40 Down: 36.04MB/s / Disk: 73.72MB/s

(20:55:00) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 24.29%/3734.87MB/00:02:36 Down: 71.46MB/s / Disk: 147.11MB/s

(20:55:01) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 24.56%/3847.91MB/00:02:37 Down: 24.02MB/s / Disk: 48.05MB/s

(20:55:02) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 25.17%/3903.96MB/00:02:35 Down: 48.32MB/s / Disk: 100.69MB/s

(20:55:03) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 25.78%/4008.43MB/00:02:33 Down: 52.48MB/s / Disk: 109.32MB/s

(20:55:04) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 26.16%/4065.39MB/00:02:33 Down: 34.62MB/s / Disk: 69.84MB/s

(20:55:05) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 26.44%/4169.64MB/00:02:34 Down: 21.77MB/s / Disk: 47.07MB/s

(20:55:07) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 27.16%/4320.84MB/00:02:33 Down: 35.24MB/s / Disk: 72.86MB/s

(20:55:08) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 28.04%/4453.27MB/00:02:30 Down: 49.91MB/s / Disk: 102.05MB/s

(20:55:10) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 28.76%/4576.01MB/00:02:29 Down: 44.1MB/s / Disk: 90.69MB/s

(20:55:11) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 29.53%/4676.76MB/00:02:26 Down: 52.92MB/s / Disk: 108.36MB/s

(20:55:12) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 29.86%/4757.24MB/00:02:26 Down: 28.13MB/s / Disk: 58.62MB/s

(20:55:13) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 30.63%/4811.40MB/00:02:23 Down: 66.55MB/s / Disk: 136.35MB/s

(20:55:14) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 31.02%/4907.91MB/00:02:23 Down: 29.84MB/s / Disk: 60.14MB/s

(20:55:15) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 31.63%/4990.51MB/00:02:22 Down: 48.38MB/s / Disk: 101.35MB/s

(20:55:16) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 32.36%/5066.74MB/00:02:19 Down: 66.58MB/s / Disk: 132.97MB/s

(20:55:17) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 32.64%/5152.32MB/00:02:19 Down: 25.59MB/s / Disk: 52.99MB/s

(20:55:19) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 33.3%/5236.11MB/00:02:18 Down: 44.85MB/s / Disk: 93.04MB/s

(20:55:20) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 34.18%/5326.78MB/00:02:15 Down: 66.01MB/s / Disk: 135.43MB/s

(20:55:22) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 34.74%/5459.18MB/00:02:15 Down: 27.26MB/s / Disk: 56.28MB/s

(20:55:23) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 35.12%/5566.26MB/00:02:14 Down: 36.44MB/s / Disk: 76.94MB/s

(20:55:24) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 36.23%/5641.08MB/00:02:10 Down: 85.83MB/s / Disk: 175.03MB/s

(20:55:25) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 36.61%/5731.44MB/00:02:11 Down: 21.18MB/s / Disk: 43.04MB/s

(20:55:26) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 37%/5860.38MB/00:02:10 Down: 32.74MB/s / Disk: 68.2MB/s

(20:55:27) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 37.94%/5948.99MB/00:02:07 Down: 76.58MB/s / Disk: 155.17MB/s

(20:55:28) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 37.99%/5998.13MB/00:02:08 Down: 4.42MB/s / Disk: 8.83MB/s

(20:55:30) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 39.21%/6141.56MB/00:02:05 Down: 55.35MB/s / Disk: 113.14MB/s

(20:55:31) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 39.59%/6239.68MB/00:02:04 Down: 34.85MB/s / Disk: 72.99MB/s

(20:55:32) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 40.31%/6300.53MB/00:02:02 Down: 61.73MB/s / Disk: 126.14MB/s

(20:55:33) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 41.03%/6411.01MB/00:02:00 Down: 60.59MB/s / Disk: 123.1MB/s

(20:55:35) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 41.8%/6533.33MB/00:01:59 Down: 34.85MB/s / Disk: 71.14MB/s

(20:55:37) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 42.24%/6649.56MB/00:01:58 Down: 35.34MB/s / Disk: 71.95MB/s

(20:55:38) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 43.18%/6767.05MB/00:01:56 Down: 52.46MB/s / Disk: 107.94MB/s

(20:55:39) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 43.4%/6847.33MB/00:01:56 Down: 19.74MB/s / Disk: 39.55MB/s

(20:55:41) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 44.65%/6965.24MB/00:01:52 Down: 68.3MB/s / Disk: 139.55MB/s

(20:55:42) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 45.37%/7053.37MB/00:01:51 Down: 59.22MB/s / Disk: 120.97MB/s

(20:55:44) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 45.87%/7187.06MB/00:01:50 Down: 26.46MB/s / Disk: 53.41MB/s

(20:55:45) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 46.91%/7285.87MB/00:01:47 Down: 75.86MB/s / Disk: 157.47MB/s

(20:55:46) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 47.02%/7367.33MB/00:01:48 Down: 6.34MB/s / Disk: 13.94MB/s

(20:55:47) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 47.85%/7430.37MB/00:01:46 Down: 77.2MB/s / Disk: 156.99MB/s

(20:55:49) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 48.29%/7577.16MB/00:01:46 Down: 22.14MB/s / Disk: 45.52MB/s

(20:55:50) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 49.29%/7676.64MB/00:01:43 Down: 61.09MB/s / Disk: 125.12MB/s

(20:55:51) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 49.4%/7723.99MB/00:01:44 Down: 9.25MB/s / Disk: 18.62MB/s

(20:55:52) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 50.06%/7846.67MB/00:01:42 Down: 47.42MB/s / Disk: 97.08MB/s

(20:55:54) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 50.5%/7922.03MB/00:01:41 Down: 36.76MB/s / Disk: 75.23MB/s

(20:55:55) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 51.6%/8038.29MB/00:01:38 Down: 74.31MB/s / Disk: 153.41MB/s

(20:55:56) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 51.99%/8140.77MB/00:01:38 Down: 23.95MB/s / Disk: 49.35MB/s

(20:55:57) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 52.76%/8238.19MB/00:01:36 Down: 61.78MB/s / Disk: 126.98MB/s

(20:55:58) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 53.15%/8306.28MB/00:01:35 Down: 32.55MB/s / Disk: 68.87MB/s

(20:55:59) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 53.43%/8426.69MB/00:01:35 Down: 23.16MB/s / Disk: 47.22MB/s

(20:56:01) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 54.2%/8492.03MB/00:01:33 Down: 57.24MB/s / Disk: 115.85MB/s

(20:56:02) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 54.76%/8572.33MB/00:01:32 Down: 50.32MB/s / Disk: 102.57MB/s

(20:56:03) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 54.82%/8588.36MB/00:01:33 Down: 4.93MB/s / Disk: 8.88MB/s

(20:56:04) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 55.42%/8677.22MB/00:01:31 Down: 56.32MB/s / Disk: 114.9MB/s

(20:56:05) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 55.87%/8740.73MB/00:01:30 Down: 35.29MB/s / Disk: 72.19MB/s

(20:56:06) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 56.03%/8821.78MB/00:01:31 Down: 13.7MB/s / Disk: 27.86MB/s

(20:56:07) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 56.75%/8895.35MB/00:01:29 Down: 54.27MB/s / Disk: 113.42MB/s

(20:56:08) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 57.3%/8982.23MB/00:01:28 Down: 43.62MB/s / Disk: 88.05MB/s

(20:56:09) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 57.63%/9071.43MB/00:01:27 Down: 26.17MB/s / Disk: 53.66MB/s

(20:56:10) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 58.51%/9177.40MB/00:01:25 Down: 60.94MB/s / Disk: 127MB/s

(20:56:12) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 59.01%/9303.18MB/00:01:25 Down: 24.79MB/s / Disk: 49.84MB/s

(20:56:13) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 60.11%/9404.57MB/00:01:22 Down: 94.16MB/s / Disk: 193.55MB/s

(20:56:15) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 60.5%/9506.11MB/00:01:21 Down: 25.77MB/s / Disk: 52.03MB/s

(20:56:16) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 60.83%/9585.62MB/00:01:21 Down: 26.32MB/s / Disk: 54.46MB/s

(20:56:17) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 61.49%/9662.86MB/00:01:19 Down: 49.51MB/s / Disk: 102.68MB/s

(20:56:18) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 61.66%/9732.81MB/00:01:19 Down: 14.73MB/s / Disk: 30.99MB/s

(20:56:19) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 62.27%/9797.87MB/00:01:18 Down: 50.4MB/s / Disk: 102.44MB/s

(20:56:21) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 63.09%/9912.98MB/00:01:16 Down: 43.12MB/s / Disk: 89.89MB/s

(20:56:22) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 63.92%/10031.37MB/00:01:14 Down: 56.21MB/s / Disk: 113.92MB/s

(20:56:23) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 64.2%/10138.38MB/00:01:14 Down: 23.83MB/s / Disk: 49.39MB/s

(20:56:24) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 65.03%/10198.96MB/00:01:12 Down: 72.08MB/s / Disk: 147.06MB/s

(20:56:25) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 65.36%/10318.62MB/00:01:11 Down: 27.02MB/s / Disk: 55.33MB/s

(20:56:26) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 65.96%/10396.76MB/00:01:10 Down: 51.55MB/s / Disk: 108.42MB/s

(20:56:27) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 66.72%/10471.74MB/00:01:08 Down: 55.06MB/s / Disk: 111.03MB/s

(20:56:28) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 66.78%/10569.95MB/00:01:08 Down: 4.7MB/s / Disk: 8.88MB/s

(20:56:30) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 67.55%/10697.80MB/00:01:07 Down: 40.69MB/s / Disk: 84.47MB/s

(20:56:31) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 68.43%/10781.45MB/00:01:05 Down: 58.96MB/s / Disk: 120.72MB/s

(20:56:32) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 69.04%/10903.14MB/00:01:04 Down: 49.93MB/s / Disk: 104.09MB/s

(20:56:34) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 69.92%/10972.88MB/00:01:01 Down: 67.51MB/s / Disk: 137.57MB/s

(20:56:35) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 70.31%/11087.08MB/00:01:01 Down: 33.28MB/s / Disk: 69.26MB/s

(20:56:36) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 70.92%/11117.29MB/00:00:59 Down: 49.18MB/s / Disk: 102.77MB/s

(20:56:37) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 71.52%/11227.44MB/00:00:58 Down: 52.54MB/s / Disk: 106.15MB/s

(20:56:38) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 72.13%/11343.22MB/00:00:57 Down: 33.73MB/s / Disk: 70.54MB/s

(20:56:39) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 72.79%/11437.94MB/00:00:55 Down: 51.2MB/s / Disk: 105.26MB/s

(20:56:39) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""

(20:56:40) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 73.62%/11533.11MB/00:00:54 Down: 72.38MB/s / Disk: 148.38MB/s

(20:56:41) INFO:    [Gog]:              GOG presence set

(20:56:42) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 74.12%/11627.65MB/00:00:53 Down: 29MB/s / Disk: 58.67MB/s

(20:56:43) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 74.94%/11749.72MB/00:00:51 Down: 50.39MB/s / Disk: 103.59MB/s

(20:56:45) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 75.77%/11864.39MB/00:00:49 Down: 43.59MB/s / Disk: 90.13MB/s

(20:56:46) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 76.49%/11990.99MB/00:00:48 Down: 57.53MB/s / Disk: 117.16MB/s

(20:56:48) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 76.99%/12095.08MB/00:00:47 Down: 27.08MB/s / Disk: 55.14MB/s

(20:56:49) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 77.96%/12220.75MB/00:00:45 Down: 69.53MB/s / Disk: 141.91MB/s

(20:56:50) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 78.63%/12314.85MB/00:00:43 Down: 48.3MB/s / Disk: 99.98MB/s

(20:56:52) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 79.23%/12362.58MB/00:00:42 Down: 34.57MB/s / Disk: 70.74MB/s

(20:56:53) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 79.45%/12472.25MB/00:00:42 Down: 13.75MB/s / Disk: 29.74MB/s

(20:56:54) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 80.17%/12538.68MB/00:00:40 Down: 65.13MB/s / Disk: 133.96MB/s

(20:56:56) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 80.83%/12662.04MB/00:00:39 Down: 35.38MB/s / Disk: 72.48MB/s

(20:56:57) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 81.5%/12743.62MB/00:00:37 Down: 55.56MB/s / Disk: 114.97MB/s

(20:56:58) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 82.1%/12830.37MB/00:00:36 Down: 52.6MB/s / Disk: 108.84MB/s

(20:56:59) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 82.54%/12931.57MB/00:00:35 Down: 35.54MB/s / Disk: 73.69MB/s

(20:57:01) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 83.48%/13056.60MB/00:00:33 Down: 42.75MB/s / Disk: 87.71MB/s

(20:57:02) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 84.25%/13182.68MB/00:00:32 Down: 43.74MB/s / Disk: 91.01MB/s

(20:57:03) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 84.86%/13271.94MB/00:00:31 Down: 47.76MB/s / Disk: 96.72MB/s

(20:57:04) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 85.58%/13361.20MB/00:00:29 Down: 60.27MB/s / Disk: 123.5MB/s

(20:57:06) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 86.3%/13448.45MB/00:00:27 Down: 60.46MB/s / Disk: 124.68MB/s

(20:57:07) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 87.12%/13554.02MB/00:00:26 Down: 48.38MB/s / Disk: 100.1MB/s

(20:57:08) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 87.56%/13652.66MB/00:00:25 Down: 35.49MB/s / Disk: 73.65MB/s

(20:57:10) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 88.17%/13730.96MB/00:00:24 Down: 37.69MB/s / Disk: 76.82MB/s

(20:57:11) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 88.87%/13855.37MB/00:00:22 Down: 37.68MB/s / Disk: 76.99MB/s

(20:57:13) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 89.42%/13935.66MB/00:00:21 Down: 36.39MB/s / Disk: 73.96MB/s

(20:57:14) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 90.14%/14033.50MB/00:00:20 Down: 59.88MB/s / Disk: 123.47MB/s

(20:57:15) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 90.69%/14126.24MB/00:00:19 Down: 35.35MB/s / Disk: 73.03MB/s

(20:57:16) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 91.41%/14216.80MB/00:00:17 Down: 63.09MB/s / Disk: 129.3MB/s

(20:57:17) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 91.69%/14284.72MB/00:00:17 Down: 16.23MB/s / Disk: 34.07MB/s

(20:57:18) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 92.4%/14398.73MB/00:00:15 Down: 62.36MB/s / Disk: 129.48MB/s

(20:57:20) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 93.01%/14495.64MB/00:00:14 Down: 42.89MB/s / Disk: 89.14MB/s

(20:57:21) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 93.4%/14592.09MB/00:00:13 Down: 30.77MB/s / Disk: 62.92MB/s

(20:57:22) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 94%/14684.05MB/00:00:12 Down: 38.17MB/s / Disk: 76.95MB/s

(20:57:23) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 95.05%/14819.45MB/00:00:10 Down: 93.43MB/s / Disk: 190.44MB/s

(20:57:25) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 95.22%/14874.09MB/00:00:09 Down: 11.18MB/s / Disk: 21.8MB/s

(20:57:26) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 95.22%/14969.85MB/00:00:09 Down: 0.49MB/s / Disk: 0MB/s

(20:57:27) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 96.32%/15043.33MB/00:00:07 Down: 59.96MB/s / Disk: 123.3MB/s

(20:57:29) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 96.98%/15179.49MB/00:00:06 Down: 37.87MB/s / Disk: 78.19MB/s

(20:57:30) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 97.2%/15270.87MB/00:00:05 Down: 22.75MB/s / Disk: 46.97MB/s

(20:57:31) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 97.92%/15343.02MB/00:00:04 Down: 46.2MB/s / Disk: 94.38MB/s

(20:57:32) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 98.53%/15397.80MB/00:00:03 Down: 53.36MB/s / Disk: 108.64MB/s

(20:57:33) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 99.08%/15510.65MB/00:00:01 Down: 42.08MB/s / Disk: 88.07MB/s

(20:57:35) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 99.91%/15603.50MB/00:00:00 Down: 40.09MB/s / Disk: 81.06MB/s

(20:57:36) INFO:    [Gog]:              Progress for Deus Ex: Human Revolution - Director’s Cut: 100%/15619.74MB/00:00:00 Down: 8.35MB/s / Disk: 14.48MB/s

(20:57:38) INFO:    [Gog]:              Got install info from cache for 1370227705 on windows platform

(20:57:38) INFO:    [Gog]:              Windows os, running setup instructions on install

(20:57:38) INFO:    [Backend]:          operation interrupted

(20:57:38) INFO:    [Gog]:              SETUP: Installing redist DirectX 9.0c

(20:57:38) INFO:    [Gog]:              SETUP: Installing redist Visual C++ Redist 2008

(20:57:38) INFO:    [Gog]:              SETUP: Installing redist Visual C++ Redist 2015

(20:57:39) INFO:    [Gog]:              Setup: Finished

(20:57:39) INFO:    [Backend]:          Adding shortcuts for Deus Ex: Human Revolution - Director’s Cut

(20:57:39) INFO:    [DownloadManager]:  Finished Installation of 1370227705

(20:57:39) INFO:    [DownloadManager]:  1370227705 added to download manager finished.

(20:57:39) INFO:    [DownloadManager]:  1370227705 removed from download manager.

(20:57:39) INFO:    [Frontend]:         Refreshing gog Library

(20:57:39) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""

(20:57:39) INFO:    [Backend]:          Stopping Power Saver Blocker

(20:57:40) INFO:    [Gog]:              Getting GOG library

(20:57:40) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""

(20:57:43) INFO:    [Gog]:              Saved games data

(20:58:01) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Beholder 3

(20:58:01) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Beholder 3

(20:58:01) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Beholder 3

(20:58:01) INFO:    [ExtraGameInfo]:    Getting GamesDB data for Beholder 3

(20:58:01) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Beholder 3

(20:58:01) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Beholder 3

(20:58:01) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Beholder 3

(20:58:01) INFO:    [ExtraGameInfo]:    Getting GamesDB data for Beholder 3

(20:58:01) INFO:    [Nile]:             Getting more details

(20:58:01) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\nile_config" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\nile`"" -Wait -NoNewWindow -ArgumentList "`"install`"","`"--info`"","`"--json`"","`"amzn1.adg.product.8cac5ece-23c0-41c4-8045-81fa6905f9f0`""

(20:58:01) INFO:    [Nile]:             Getting more details

(20:58:01) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\nile_config" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\nile`"" -Wait -NoNewWindow -ArgumentList "`"install`"","`"--info`"","`"--json`"","`"amzn1.adg.product.8cac5ece-23c0-41c4-8045-81fa6905f9f0`""

(20:58:02) ERROR:   [ExtraGameInfo]:    Got AxiosError when sending HowLongToBeat request for Beholder 3: {

  "message": "Request failed with status code 404",

  "name": "AxiosError",

  "stack": "AxiosError: Request failed with status code 404\n    at settle (C:\\Users\\Leander Tau\\AppData\\Local\\Programs\\heroic\\resources\\app.asar\\node_modules\\axios\\lib\\core\\settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (C:\\Users\\Leander Tau\\AppData\\Local\\Programs\\heroic\\resources\\app.asar\\node_modules\\axios\\lib\\adapters\\http.js:599:11)\n    at IncomingMessage.emit (node:events:531:35)\n    at endReadableNT (node:internal/streams/readable:1696:12)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Axios.request (C:\\Users\\Leander Tau\\AppData\\Local\\Programs\\heroic\\resources\\app.asar\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at Lu (C:\\Users\\Leander Tau\\AppData\\Local\\Programs\\heroic\\resources\\app.asar\\build\\main\\main.js:7:3251)\n    at async Promise.all (index 1)\n    at Ao (C:\\Users\\Leander Tau\\AppData\\Local\\Programs\\heroic\\resources\\app.asar\\build\\main\\main.js:7:6290)\n    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:83537)",

  "config": {

    "transitional": {

      "silentJSONParsing": true,

      "forcedJSONParsing": true,

      "clarifyTimeoutError": false

    },

    "adapter": [

      "xhr",

      "http",

      "fetch"

    ],

    "transformRequest": [

      null

    ],

    "transformResponse": [

      null

    ],

    "timeout": 0,

    "xsrfCookieName": "XSRF-TOKEN",

    "xsrfHeaderName": "X-XSRF-TOKEN",

    "maxContentLength": -1,

    "maxBodyLength": -1,

    "env": {},

    "headers": {

      "Accept": "*/*",

      "Content-Type": "application/json",

      "User-Agent": "HeroicGamesLauncher/2.16.1",

      "Referer": "https://howlongtobeat.com/",

      "Content-Length": "347",

      "Accept-Encoding": "gzip, compress, deflate, br"

    },

    "method": "post",

    "url": "https://www.howlongtobeat.com/api/search",

    "data": "{\"searchType\":\"games\",\"searchTerms\":[\"Beholder\",\"3\"],\"searchPage\":1,\"size\":20,\"searchOptions\":{\"games\":{\"userId\":0,\"platform\":\"\",\"sortCategory\":\"popular\",\"rangeCategory\":\"main\",\"rangeTime\":{\"min\":0,\"max\":0},\"gameplay\":{\"perspective\":\"\",\"flow\":\"\",\"genre\":\"\"},\"modifier\":\"\"},\"users\":{\"sortCategory\":\"postcount\"},\"filter\":\"\",\"sort\":0,\"randomizer\":0}}"

  },

  "code": "ERR_BAD_REQUEST",

  "status": 404

}

(20:58:02) ERROR:   [ExtraGameInfo]:    Got AxiosError when sending HowLongToBeat request for Beholder 3: {

  "message": "Request failed with status code 404",

  "name": "AxiosError",

  "stack": "AxiosError: Request failed with status code 404\n    at settle (C:\\Users\\Leander Tau\\AppData\\Local\\Programs\\heroic\\resources\\app.asar\\node_modules\\axios\\lib\\core\\settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (C:\\Users\\Leander Tau\\AppData\\Local\\Programs\\heroic\\resources\\app.asar\\node_modules\\axios\\lib\\adapters\\http.js:599:11)\n    at IncomingMessage.emit (node:events:531:35)\n    at endReadableNT (node:internal/streams/readable:1696:12)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Axios.request (C:\\Users\\Leander Tau\\AppData\\Local\\Programs\\heroic\\resources\\app.asar\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at Lu (C:\\Users\\Leander Tau\\AppData\\Local\\Programs\\heroic\\resources\\app.asar\\build\\main\\main.js:7:3251)\n    at async Promise.all (index 1)\n    at Ao (C:\\Users\\Leander Tau\\AppData\\Local\\Programs\\heroic\\resources\\app.asar\\build\\main\\main.js:7:6290)\n    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:83537)",

  "config": {

    "transitional": {

      "silentJSONParsing": true,

      "forcedJSONParsing": true,

      "clarifyTimeoutError": false

    },

    "adapter": [

      "xhr",

      "http",

      "fetch"

    ],

    "transformRequest": [

      null

    ],

    "transformResponse": [

      null

    ],

    "timeout": 0,

    "xsrfCookieName": "XSRF-TOKEN",

    "xsrfHeaderName": "X-XSRF-TOKEN",

    "maxContentLength": -1,

    "maxBodyLength": -1,

    "env": {},

    "headers": {

      "Accept": "*/*",

      "Content-Type": "application/json",

      "User-Agent": "HeroicGamesLauncher/2.16.1",

      "Referer": "https://howlongtobeat.com/",

      "Content-Length": "347",

      "Accept-Encoding": "gzip, compress, deflate, br"

    },

    "method": "post",

    "url": "https://www.howlongtobeat.com/api/search",

    "data": "{\"searchType\":\"games\",\"searchTerms\":[\"Beholder\",\"3\"],\"searchPage\":1,\"size\":20,\"searchOptions\":{\"games\":{\"userId\":0,\"platform\":\"\",\"sortCategory\":\"popular\",\"rangeCategory\":\"main\",\"rangeTime\":{\"min\":0,\"max\":0},\"gameplay\":{\"perspective\":\"\",\"flow\":\"\",\"genre\":\"\"},\"modifier\":\"\"},\"users\":{\"sortCategory\":\"postcount\"},\"filter\":\"\",\"sort\":0,\"randomizer\":0}}"

  },

  "code": "ERR_BAD_REQUEST",

  "status": 404

}

(20:59:27) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\legendaryConfig\legendary" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"egl-sync`"","`"-y`"","`"--enable-sync`""

(20:59:28) INFO:    [Legendary]:        Checking for importable games...

Nothing to import.



Checking for exportable games...

Nothing to export.



Checking automatic sync...

(20:59:28) INFO:    [Backend]:          Heroic: Setting egsLinkedPath to "windows" (previous value: undefined)

(20:59:28) INFO:    [Frontend]:         Refreshing undefined Library

(20:59:28) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager

(20:59:28) INFO:    [Legendary]:        Refreshing library...

(20:59:28) INFO:    [Nile]:             Refreshing library...

(20:59:28) INFO:    [Nile]:             Refreshing Amazon Games...

(20:59:28) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\nile_config" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\nile`"" -Wait -NoNewWindow -ArgumentList "`"library`"","`"sync`""

(20:59:28) INFO:    [Nile]:             Game list updated, got 40 games

(20:59:28) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""

(20:59:29) INFO:    [Gog]:              Getting GOG library

(20:59:29) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""

(20:59:31) INFO:    [Gog]:              Saved games data

(20:59:35) INFO:    [Backend]:          Heroic: Setting autoUpdateGames to true (previous value: false)

(20:59:43) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\legendaryConfig\legendary" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"--version`""

(20:59:43) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"--version`""

(20:59:43) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\nile_config" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\nile`"" -Wait -NoNewWindow -ArgumentList "`"--version`""

(20:59:43) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: LEGENDARY_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\legendaryConfig\legendary" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"eos-overlay`"","`"info`""

(20:59:44) INFO:    [Legendary]:        Abort command "LEGENDARY_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\legendaryConfig\legendary" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"eos-overlay`"","`"info`"""

(20:59:54) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\legendaryConfig\legendary" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"--version`""

(20:59:54) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"--version`""

(20:59:54) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\nile_config" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\nile`"" -Wait -NoNewWindow -ArgumentList "`"--version`""

(21:01:39) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""

(21:01:41) INFO:    [Gog]:              GOG presence set

(21:06:39) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="C:\Users\Leander Tau\AppData\Roaming\heroic\gogdlConfig" powershell -NoProfile Start-Process "`"C:\Users\Leander Tau\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\Leander Tau\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""

(21:06:41) INFO:    [Gog]:              GOG presence set
```

### Steps to reproduce

Go to Stores, Epic Store, click the sign in button.

### Expected behavior

Anticipated a successful sign-in but got an error instead.

### Screenshots

Image

### Heroic Version

Latest Stable

### System Information

Windows 11 Pro 24H2 26100.3476
AMD CPU

### Additional information

I had successfully signed in during the days prior to the problem.  When the problem occurred, I was signed out of Epic automatically when I launched Heroic and I haven't been able to sign back in since then.

### LINKED ISSUE #4477: Epic login broken on 2.16.1
### Describe the bug

Dear developers,

I found out that the epic login is broken on 2.16.1 release

There is a message from Epic: Invalid Response, logging from the browser mentions: parameter client_id missing

rolling back to 2.15.2 solves the issue for me.

Thank you.

### Add logs

```text
(18:04:45) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary

(18:04:45) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl

(18:04:45) INFO:    [Connection]:       Connectivity: check-online

(18:04:45) INFO:    [Connection]:       Pinging external endpoints

(18:04:45) INFO:    [Gog]:              Checking for existing gog manifests

(18:04:45) WARNING: [Backend]:          Protocol already registered.

(18:04:45) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/genci/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary --version

(18:04:45) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/genci/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/genci/.config/heroic/gog_store/auth.json --version

(18:04:45) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/genci/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile --version

(18:04:45) INFO:    [Frontend]:         Refreshing undefined Library

(18:04:45) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager

(18:04:45) INFO:    [Legendary]:        Refreshing library...

(18:04:45) INFO:    [Legendary]:        Refreshing Epic Games...

(18:04:45) INFO:    [Backend]:          Frontend Ready

(18:04:45) INFO:    [Connection]:       Connectivity: online

(18:04:45) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present

(18:04:45) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/genci/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/genci/.config/heroic/gog_store/auth.json auth

(18:04:45) INFO:    [Backend]:          Checking for new Heroic Updates

(18:04:45) INFO:    [Backend]:          Checking for current version changelog

(18:04:45) INFO:    [Backend]:          

System Information:

CPU: 20x 13th Gen Intel(R) Core(TM) i5-13600KF

Memory: 24.22 GB (used: 4.47 GB)

GPUs:

  GPU 0:

    Name: NVIDIA Corporation GA104 [GeForce RTX 3060 Ti Lite Hash Rate]

    IDs: D=2489 V=10de SD=153c SV=10de

    Driver: nvidia

OS: Ubuntu 25.04 (Plucky Puffin) (linux)

The current system is not a Steam Deck

We are not running inside a Flatpak container

Software Versions:

  Heroic: 2.16.1 Scopper Gaban

  Legendary: 0.20.36 Urban Flight (Heroic)

  gogdl: 1.1.2

  comet: comet 0.2.0

  Nile: 1.1.2 Will A. Zeppeli

(18:04:45) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/genci/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary list --third-party

(18:04:45) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded

(18:04:47) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found

(18:04:47) INFO:    [Winetricks]:       Downloading Winetricks

(18:04:49) INFO:    [Legendary]:        Game list updated, got 140 games & DLCs

(18:04:49) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager

(18:04:49) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/genci/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary list --third-party

(18:04:50) INFO:    [WineDownloader]:   Updating wine versions info

(18:04:50) INFO:    [WineDownloader]:   Fetching upstream information...

(18:04:50) INFO:    [Backend]:          Starting the Download Queue

(18:04:50) INFO:    [WineDownloader]:   wine versions updated

(18:04:52) WARNING: [Legendary]:        Failed to parse games from /home/genci/.config/heroic/legendaryConfig/legendary/installed.json with: Error: ENOENT: no such file or directory, open '/home/genci/.config/heroic/legendaryConfig/legendary/installed.json'

    at Object.readFileSync (node:fs:448:20)

    at Object.t.readFileSync (node:electron/js2c/node_init:2:10245)

    at Module.na (/opt/Heroic/resources/app.asar/build/main/main.js:124:3825)

    at /opt/Heroic/resources/app.asar/build/main/main.js:199:2384

    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:83537)

(18:04:52) INFO:    [Legendary]:        Found 0 games to update

(18:04:52) INFO:    [Frontend]:         No cache found, getting data from legendary...

(18:04:52) INFO:    [Legendary]:        Refreshing library...

(18:04:52) INFO:    [Legendary]:        Refreshing Epic Games...

(18:04:52) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/genci/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary list --third-party

(18:04:54) INFO:    [Legendary]:        Game list updated, got 140 games & DLCs

(18:04:54) INFO:    [Frontend]:         Force Update
```

### Steps to reproduce

1. try to login to epic
2. insert credentials
3. click the login button
4. enter 2fa code
5. the error comes out as in the screenshot

Trying with the firefox browser:
- Either it pops out the meesage after logging in: incorrect parameter client_id
- Or it logs you in in firefox, but nothing happens back in heroic launcher and the user remains logged out with the same error as it was before

### Expected behavior

Epic login with 2FA authentication needs to work.

### Screenshots

Image

### Heroic Version

Latest Stable

### System Information

OS: Ubuntu 25.04, CachyOS latest March 25 Release, probably others affected
GPU: Nvidia 3060 TI
CPU: intel 13600KF

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by imLinguin**
This should address the login issue. In the meantime simply going through Heroic's Manage Accounts page will let users log in. 
This PR fixes the regression when going to login through Stores tab

Closes #4477 
Closes #4460
Closes #4433 
Closes #4419 
Closes #4289
Closes #4223
Closes #4430

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

File: src/frontend/screens/WebView/index.tsx [hunk 1]
```diff
@@ -151,6 +151,14 @@ export default function WebView() {
     if (webview) {
       const loadstop = async () => {
         setLoading({ ...loading, refresh: false })
+        const userAgent =
+          startUrl === epicLoginUrl
+            ? 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) EpicGamesLauncher'
+            : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/200.0'
+        if (webview.getUserAgent() != userAgent) {
+          webview.setUserAgent(userAgent)
+          console.log(userAgent)
```
Comment (Etaash-mathamsetty) [inline src/frontend/screens/WebView/index.tsx:160]: looks good, maybe get rid of this console.log tho

**Comment by Etaash-mathamsetty** [comment]
> Just curious, why is the `at runtime` part needed? I think it would be good to add a comment about that in the code so we don't break this accidentally in a refactor or something

Otherwise the user agent is only set once for the first URL and is never updated again

File: src/frontend/screens/WebView/index.tsx (hunk 1 above)
Comment (imLinguin) [reply src/frontend/screens/WebView/index.tsx:160]: forgot about that

**Review by Etaash-mathamsetty — APPROVED** [review]
lgtm

**Review by CommandMC — APPROVED** [review]
