### PR TITLE
Change Game Language

### LINKED ISSUE #1391: Prey launches in the language specified in the windows regional format instead of Heroic's app language setting
### Describe the bug

There is a bug where Prey (https://store.epicgames.com/en-US/p/prey) starts in the language specified in Windows' regional format (see screenshot 1) instead of the app language set inside the Heroic (screenshot 2).

The behavior differs from the Epic Games launcher, as Prey launches in the language specified in the Epic Games language setting (screenshot 3).

The game does not have a setting ingame to change text language in its option menu (only an option for audio language).
This may affect other games but Prey is the first one where I have noticed it.

### Add logs

```
(21:40:19) DEBUG:   [Legendary]:       Running Legendary command: C:\Users\Me\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(21:40:23) INFO:    [Legendary]:       Legendary location: C:\Users\Me\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary
(21:40:23) INFO:    [Gog]:             GOGDL location: C:\Users\Me\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl
(21:40:23) INFO:    [Backend]:         
  Heroic Version: 2.3.3 Brook
  Legendary Version:  0.20.25 Our Benefactors
  OS: Microsoft Windows 11 Pro KERNEL: 10.0.22000 ARCH: x64
  CPU: AMD Ryzen 5 3600 6-Core Processor @3.6 
  RAM: Total: 15.93 GiB Available: 9.79 GiB
  GRAPHICS: GPU0: NVIDIA GeForce RTX 2060 VRAM: 6144MB DRIVER: 511.79 
  
  
(21:40:23) WARNING: [Backend]:         Protocol already registered.
(21:40:24) INFO:    [Frontend]:        Refreshing Library
(21:40:24) INFO:    [Legendary]:       Refreshing library...
(21:40:24) INFO:    [Legendary]:       Refreshing Epic Games...
(21:40:24) DEBUG:   [Legendary]:       Running Legendary command: C:\Users\Me\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list
(21:40:26) INFO:    [Legendary]:       Updating game list
(21:40:26) INFO:    [Legendary]:       Game List Updated
(21:40:26) INFO:    [Legendary]:       Checking for game updates: C:\Users\Me\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list-installed --check-updates --tsv
(21:40:26) DEBUG:   [Legendary]:       Running Legendary command: C:\Users\Me\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list-installed --check-updates --tsv
(21:40:27) INFO:    [Legendary]:       Found 0 game(s) to update
(21:40:27) INFO:    [Gog]:             Found 0 game(s) to update
(21:40:30) INFO:    [Backend]:         Launching PREY (52d88e9a6df248da913c8e99f1e4c526)
(21:40:30) INFO:    [Legendary]:       Launching PREY: C:\Users\Me\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary launch 52d88e9a6df248da913c8e99f1e4c526
(21:40:30) DEBUG:   [Legendary]:       Running Legendary command: C:\Users\Me\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary launch 52d88e9a6df248da913c8e99f1e4c526
(21:40:31) DEBUG:   [Legendary]:       Running Legendary command: C:\Users\Me\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(21:40:35) INFO:    [Backend]:         Log was written to C:\Users\Me\AppData\Roaming\heroic\GamesConfig\52d88e9a6df248da913c8e99f1e4c526-lastPlay.log
(21:40:35) INFO:    [Frontend]:        Refreshing Library
(21:40:35) INFO:    [Legendary]:       Refreshing library...
(21:40:35) INFO:    [Legendary]:       Updating game list
(21:40:35) INFO:    [Legendary]:       Game List Updated
```

### Steps to reproduce

1. Set the app language in Heroic to English.
2. Set the regional format in Windows to any non-english region (e.g. German (Germany) in my case).
3. Launch Prey via Heroic.
4. Prey starts with german text language.

### Expected behavior

Prey starts with english text language like it does for the Epic Games Launcher.

### Screenshots

image
Screenshot 1 of Windows regional format settings

image
Screenshot 2 of Heroic language setting

image
Screenshot 3 of Epic Games language setting

### System Information

- OS [e. g. "Ubuntu"]: Windows 11 Version 21H2
- Heroic Version [e. g. 2.1.1]: 2.3.3

### Additional information

_No response_

### LINKED ISSUE #1432: Games try to launch in the language specified in the system instead of Heroic's app language setting
### Describe the bug

When I launch, for example, Wolfenstein: The new Order, the game starts in English instead to do it on Spanish, as Heroic is configured. This is because my system language is Galician, and as that language is not in the game's language list, it defaults to English. Minority language users should be able to configure this. 

I configured my system on Spanish and now I can play the game on this language, but I prefer to use my OS on my native language.

### Add logs

Launch Command: DXVK_HUD=fps /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch a64dcf9b711a4a60a3c0b6f052dfc7da --wine /usr/bin/wine --wine-prefix /media/COMP/WINEDRIVE/HEROIC/PREFIXES/WolfensteinTNO

System Info:
Heroic Version: 2.3.7 Brook
Legendary Version:  0.20.26 Dark Energy
OS: Ubuntu KERNEL: 5.15.0-33-generic ARCH: x64
CPU: AMD Ryzen 7 5800X 8-Core Processor @3.8 GOVERNOR: schedutil
RAM: Total: 31.26 GiB Available: 28.48 GiB
GRAPHICS: GPU0: NVIDIA GeForce RTX 3070 VRAM: 8192MB DRIVER: 510.73.05 
PROTOCOL: x11

Game Settings: {
	"checkUpdatesInterval": 10,
	"enableUpdates": false,
	"addDesktopShortcuts": false,
	"addStartMenuShortcuts": false,
	"autoInstallDxvk": true,
	"autoInstallVkd3d": true,
	"checkForUpdatesOnStartup": true,
	"customWinePaths": [],
	"defaultInstallPath": "/media/COMP/WINEDRIVE/HEROIC",
	"defaultWinePrefix": "/media/COMP/WINEDRIVE/HEROIC/PREFIXES",
	"language": "en",
	"maxWorkers": 0,
	"minimizeOnLaunch": false,
	"nvidiaPrime": false,
	"otherOptions": "",
	"showUnrealMarket": false,
	"showFps": true,
	"useGameMode": false,
	"userInfo": {
		"epicId": "1900a872a3e1475492dd721838e286ed",
		"name": "leo"
	},
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/media/COMP/WINEDRIVE/HEROIC/PREFIXES/WolfensteinTNO",
	"wineVersion": {
		"bin": "/usr/bin/wine",
		"name": "Wine Default - wine-7.3 (Staging)"
	},
	"altLegendaryBin": "",
	"altGogdlBin": "",
	"disableController": false,
	"egsLinkedPath": "",
	"maxRecentGames": 5,
	"maxSharpness": 2,
	"savesPath": "/media/COMP/WINEDRIVE/HEROIC/PREFIXES/WolfensteinTNO/drive_c/users/leo/Saved Games/MachineGames/Wolfenstein The New Order/base/savegame/1900a872a3e1475492dd721838e286ed/",
	"targetExe": ""
}

Error Log:
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching a64dcf9b711a4a60a3c0b6f052dfc7da...
002c:fixme:winediag:LdrInitializeThunk wine-staging 7.7 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
00f8:fixme:heap:RtlSetHeapInformation 0000000002DB0000 0 000000000011F6E0 4 stub
00f8:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
00fc:fixme:heap:RtlSetHeapInformation 0000000000230000 0 000000000374FD58 4 stub
00fc:fixme:reg:RegQueryInfoKeyA security argument not supported.
00fc:fixme:reg:RegQueryInfoKeyA security argument not supported.
00fc:fixme:reg:RegQueryInfoKeyA security argument not supported.
0190:fixme:imm:ImeSetActiveContext (0x133d3610, 1): stub
0190:fixme:imm:ImmReleaseContext (000000000001008E, 00000000133D3610): stub
0080:fixme:imm:ImeSetActiveContext (0x55080, 0): stub
0080:fixme:imm:ImmReleaseContext (0000000000010020, 0000000000055080): stub
00fc:fixme:rawinput:RegisterRawInputDevices Unhandled flags 0x230 for device 0.
00fc:fixme:thread:SetThreadIdealProcessor (00000000000005B4 0): stub
00fc:fixme:thread:SetThreadIdealProcessor (00000000000005C0 1): stub
00fc:fixme:thread:SetThreadIdealProcessor (00000000000005D0 2): stub
00fc:fixme:ole:CoInitializeSecurity 0000000000000000, -1, 0000000000000000, 0000000000000000, 0, 3, 0000000000000000, 0, 0000000000000000 stub
00fc:fixme:wbemprox:wbem_locator_ConnectServer unsupported flags
00fc:fixme:wbemprox:client_security_SetBlanket 0000000029A1FDE0, 000000000277D1A0, 10, 0, (null), 3, 3, 0000000000000000, 0
00fc:fixme:wbemprox:client_security_Release 0000000029A1FDE0
0058:fixme:mountmgr:query_property Faking StorageDeviceProperty data
0058:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
0058:fixme:mountmgr:query_property Faking StorageDeviceProperty data
0058:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
0058:fixme:mountmgr:query_property Faking StorageDeviceProperty data
0058:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
0058:fixme:mountmgr:query_property Faking StorageDeviceProperty data
0058:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
01f4:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
01f4:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
00fc:fixme:rawinput:RegisterRawInputDevices Unhandled flags 0x230 for device 0.
0190:fixme:msg:pack_message msg 14 (WM_ERASEBKGND) not supported yet

### Steps to reproduce

1. Go to 'Wolfenstein: The new Order' game 
2. Click on Play
3. See the game on English

### Expected behavior

To play the game on Spanish, and have the possibility of configure this.

### Screenshots

_No response_

### System Information

- OS: Ubuntu 22.04
- Heroic Version : 2.3.7

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by arielj**
This PR adds the feature to set the game language through Heroic for the games that support it.

Each game now has a `Preferred Language` setting:

image

Users can set a language code to pass as the `--language` flag to legendary.

Is left empty, the preferred language will fallback to Heroic's language configuration to mimic Epic Games Launcher's behavoir.

This fixes #1391 and fixes #1432

I only know of those 2 games that support this setting (Prey and Wolfenstein The New Order), I tested this with Prey. I couldn't find any place where I could know if a game should/shouldn't support this, I found no flags anywhere in the json files.

Also, I understand there's no equivalent flag for GOG games, so I just implemented this for Epic games, I'm not sure if this should be hidden when the game is from GOG or if there's actually some flag for this (I'll ask over discord). I this this can be reviewed anyway?

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

File: src/index.tsx [hunk 1]
```diff
@@ -24,6 +24,13 @@ initShortcuts()
 
 const storage: Storage = window.localStorage
 
+let languageCode = configStore.get('language')
+
+if (!languageCode) {
+  languageCode = storage.getItem('language') || 'en'
+  configStore.set('language', languageCode)
+}
```
Comment (arielj) [inline src/index.tsx:32]: we were only storing the apps language in the browser's local storage, but that's inaccessible from the backend for the launch command

this block will backfill the user's language in the config store, it's kinda ugly but I couldn't find a better way to do this

another option is to NOT backfill the config value but I imagine users will think it's a bug if the OS and Heroic has different languages

**Comment by JakobDev** [comment]
I personally would prefer a DropDown Menu instead of a Textbox.

**Comment by JakobDev** [comment]
Probably adding a other element in the List would be a solution. If you selected that, the Inputfield appears. I don't know, if that easily possible. The problem with the current solution is, that average Users which are not interested in technic may not know the correct language code or what that word even means.

**Comment by arielj** [comment]
> Probably adding a other element in the List would be a solution. If you selected that, the Inputfield appears. I don't know, if that easily possible. The problem with the current solution is, that average Users which are not interested in technic may not know the correct language code or what that word even means.

One comment though, the logic is that it will default to Heroic's language, so for most users they'll probable never have to deal with this configuration if they set the language of Heroic to their preferred language, this is more like an advanced feature already to override heroic's language for the game.

I wonder how often a user would want a language different than the une they set heroic to

**Comment by arielj** [comment]
> To be honest, I think we should not have the Input. First, it doesn't work for all games, second, will be one more option and this might be confusing to some people. And third, the game will use heroic language so the person just need to change heroic language to make it work. I think would be better to remove it. What do you think?

maybe put it in the advanced section? I'm thinking what if you want your game in a language that is not supported by heroic? then you won't be able to set it anywhere and the game will fallback to heroic's language

**Comment by arielj** [comment]
well now I'm thinking, if we support all languages already supported by EGL then I imagine games already know those are the options to support by this config, and then we can just do that and remove the intput

I just don't want to exclude languages without knowing if that's going to be a problem

**Comment by flavioislima** [comment]
Hmm, ok then put on advanced 👍

**Comment by arielj** [comment]
> Hmm, ok then put on advanced +1

hmmm I just noticed we don't have an Advanced settings section for games settings, it feels too much to add a new section just for it, maybe I can put it at the end of the current section to make it less important?

**Comment by flavioislima** [comment]
Ok

**Comment by leillo1975** [comment]
Thanks a lot!
