### PR TITLE
[UI/UX] Improve error handling on BE and FE

### LINKED ISSUE #1354: [Linux] Launching Heroic shows grey background and nothing else happens
### Describe the bug

When I open Heroic, it just shows a grey background.

### Add logs

```log
2503:0522/114829.425825:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[2503:0522/114829.425850:ERROR:select_file_dialog_linux_portal.cc(242)] Failed to read portal version property
(11:48:29) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[2532:0522/114829.467937:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
/bin/sh: line 1: hostname: command not found
(11:48:29) INFO:    [Legendary]:       Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(11:48:29) INFO:    [Gog]:             GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(11:48:29) INFO:    [Backend]:
  Heroic Version: 2.3.3 Brook
  Legendary Version:  0.20.25 Our Benefactors
  OS: Arch KERNEL: 5.17.9-arch1-1 ARCH: x64
  CPU: AMD Ryzen 5 5600G with Radeon Graphics @2.86 GOVERNOR: schedutil
  RAM: Total: 27.37 GiB Available: 25.8 GiB
  GRAPHICS: GPU0: Cezanne VRAM: 512MB DRIVER:
  PROTOCOL: wayland

APPIMAGE env is not defined, current application is not an AppImage
(11:48:29) WARNING: [Backend]:         Protocol already registered.
[2503:0522/114829.979205:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2503:0522/114829.979247:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2503:0522/114829.979274:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2532:0522/114834.113318:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[2532:0522/114911.839186:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[2532:0522/114914.080668:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```

### Steps to reproduce

1. Launch Heroic either from the menu system or from the command line
2. The UI does not display

### Expected behavior

The UI would actually display.

### Screenshots

unknown

### System Information

- OS: Arch
- Heroic Version: 2.3.3
- I'm on Wayland

### Additional information

_No response_

### LINKED ISSUE #1365: [Linux] Steam Runtime setting not updating
### Describe the bug

I am using a Steam Deck with Heroic installed via Discover. When I attempt to run a game with the new Steam runtime setting enabled, the game will not load. The game will load if the setting is disabled. Additionally, the next time I open the settings, the checkbox will be checked again even if I did not specifically enable the runtime setting.

### Steam Runtime enabled:

```
Launch Command: STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/.steam/steam STEAM_COMPAT_DATA_PATH=/home/deck/Games/Heroic/Prefixes/20XX /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Quail --no-wine --wrapper "/home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point -- '/home/deck/.steam/steam/steamapps/common/Proton 7.0/proton' waitforexitandrun"
 
System Info:
 
  Heroic Version: 2.3.3 Brook
  Legendary Version:  0.20.25 Our Benefactors
  OS: Freedesktop.org KERNEL: 5.13.0-valve14-1-neptune-02195-g5b0f749d00fa ARCH: x64
  CPU: AMD Custom APU 0405 @1.97 GOVERNOR: schedutil
  RAM: Total: 14.49 GiB Available: 11.42 GiB
  GRAPHICS: GPU0: Device 163f VRAM: 512MB DRIVER:  
  PROTOCOL: x11
 
 
Game Settings: {
	"audioFix": false,
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"autoSyncSaves": true,
	"enableEsync": false,
	"enableFsync": false,
	"maxSharpness": 2,
	"nvidiaPrime": false,
	"offlineMode": false,
	"otherOptions": "",
	"savesPath": "/home/deck/Games/Heroic/Prefixes/20XX/pfx/drive_c/users/steamuser/Documents/20XX/",
	"showFps": false,
	"showMangohud": false,
	"targetExe": "",
	"useGameMode": false,
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/home/deck/Games/Heroic/Prefixes/20XX",
	"wineVersion": {
		"bin": "/home/deck/.steam/steam/steamapps/common/Proton 7.0/proton",
		"name": "Proton - Proton 7.0",
		"type": "proton"
	},
	"useSteamRuntime": true
}
 
Error Log:
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Quail...
pressure-vessel-wrap[810]: W: /dev/shm not shared between app instances (flatpak#4214). The Steam Overlay will not work.
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
Invalid MIT-MAGIC-COOKIE-1 key
```

### Steam runtime disabled:

```
Launch Command: STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/.steam/steam STEAM_COMPAT_DATA_PATH=/home/deck/Games/Heroic/Prefixes/20XX /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Quail --no-wine --wrapper "'/home/deck/.steam/steam/steamapps/common/Proton 7.0/proton' run"
 
System Info:
 
  Heroic Version: 2.3.3 Brook
  Legendary Version:  0.20.25 Our Benefactors
  OS: Freedesktop.org KERNEL: 5.13.0-valve14-1-neptune-02195-g5b0f749d00fa ARCH: x64
  CPU: AMD Custom APU 0405 @2.99 GOVERNOR: schedutil
  RAM: Total: 14.49 GiB Available: 11.15 GiB
  GRAPHICS: GPU0: Device 163f VRAM: 512MB DRIVER:  
  PROTOCOL: x11
 
 
Game Settings: {
	"audioFix": false,
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"autoSyncSaves": true,
	"enableEsync": false,
	"enableFsync": false,
	"maxSharpness": 2,
	"nvidiaPrime": false,
	"offlineMode": false,
	"otherOptions": "",
	"savesPath": "/home/deck/Games/Heroic/Prefixes/20XX/pfx/drive_c/users/steamuser/Documents/20XX/",
	"showFps": false,
	"showMangohud": false,
	"targetExe": "",
	"useGameMode": false,
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/home/deck/Games/Heroic/Prefixes/20XX",
	"wineVersion": {
		"bin": "/home/deck/.steam/steam/steamapps/common/Proton 7.0/proton",
		"name": "Proton - Proton 7.0",
		"type": "proton"
	},
	"useSteamRuntime": false
}
 
Error Log:
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Quail...
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
Unable to read VR Path Registry from C:\users\steamuser\AppData\Local\openvr\openvrpaths.vrpath
 
Game Log:
Time: Mon May 23 17:18:04 2022
```

### Steps to reproduce

1. Attempt to run game with Steam Runtime enabled (fails)
2. Change setting to disable Steam Runtime
3. Attempt to run game (succeeds)

### Expected behavior

Expected to run with Steam Runtime enabled.

### Screenshots

_No response_

### System Information

Steam Deck, most recent beta OS
Heroic 2.3.3

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by flavioislima**
Also Trying to fix #1354 #1360 #1347 #1371 

- Introduces an Error component that we can use to treat front-end errors.
- I am now checking if no library is available and showing it, but we should start using it on most components that could return an error.
- Add on gamepage as well for when we get error from backend on `info` command
- Added try/catch blocks in several places especially on `JSON.parse()` to handle corrupted JSON files that makes Heroic not load, even if there is a damn comma by the end of the file.
- Added more error messages to `ErrorHandler` to deal with credentials expired for both GOG and Legendary. Let me know if I forgot some.
- Added some defaults returns to `electron-store` calls that could make Heroic hangs on start.
- Added new context menu to settings with options to copy Config (game and global) and open config file with the editor.
- Added handler to retry a game installation if it fails because of Memory errors. Right now its hardcoded to 5000, can be improved in the future.
- Changed how the Login Webview works by using events instead of setTimeout. On my tests it seems more reliable.
- Changed Logout handlers to erase the epic username as well, since this was causing the login state to not always update correctly.
- Fix #1365 
- Implement #1374 

image
image

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [x] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

File: electron/launcher.ts [hunk 1]
```diff
@@ -502,10 +514,23 @@ async function runLegendaryOrGogdlCommand(
...
     })
     .catch((error) => {
-      errorHandler({ error, logPath: options?.logFile })
+      if (error === 'MemoryError:') {
+        logWarning(
+          'Install failed, trying again with higher limit',
+          LogPrefix.Legendary
+        )
+        return { stdout: '', stderr: '', fullCommand: safeCommand, error }
+      }
```
Comment (CommandMC) [inline electron/launcher.ts:523]: This should be in `LegendaryGame.install` instead

File: electron/launcher.ts [hunk 2]
```diff
@@ -484,11 +485,22 @@ async function runLegendaryOrGogdlCommand(
...
+        runner: runner.name
       })
+
+      if (stderr.join().includes('ERROR')) {
+        rej(stderr.join())
+      }
+
+      if (stderr.join().includes('MemoryError:')) {
+        rej('MemoryError:')
+      }
```
Comment (CommandMC) [inline electron/launcher.ts:498]: It might be better if we'd just reject the promise here and let `LegendaryGame.install` handle figuring out what the exact error was

File: electron/legendary/games.ts [hunk 3]
```diff
@@ -403,16 +403,29 @@ class LegendaryGame extends Game {
...
     })
 
-    if (res.error) {
-      logError(
-        ['Failed to install', `${this.appName}:`, res.error],
-        LogPrefix.Legendary
+    // try to run the install again with higher memory limit
+    if (res.error === 'MemoryError:') {
+      res = await runLegendaryCommand(
+        [...commandParts, '--max-shared-memory', '5000'],
```
Comment (CommandMC) [inline electron/legendary/games.ts:414]: I'd say it would be better to obtain the shared memory requirement from the legendary output, even 5000MiB might not be enough for some games

File: electron/logger/logger.ts [hunk 4]
```diff
@@ -69,13 +76,18 @@ const getPrefixString = (prefix: LogPrefix) => {
 export function logDebug(
```
Comment (CommandMC) [inline electron/logger/logger.ts:76]: Seeing all of the repeated code here, maybe we should have a base logging function that gets the level and prefix passed to it instead

File: electron/launcher.ts (hunk 1 above)
Comment (flavioislima) [reply electron/launcher.ts:523]: It is more complicated than that. 
Right now the install command fails silently, the promise is not rejected since the message from legendary is not an error.
So I needed a workaround and the only time I get this info, the MemoryError is on the `launchCommand` 
Dont know if that's what you mean

File: electron/legendary/games.ts (hunk 3 above)
Comment (flavioislima) [reply electron/legendary/games.ts:414]: I think will work for 99% of the games. I mean, I never had any issue with this even before Heroic, when using legendary only. So its an edge case deal with the string output is too boring.

File: electron/logger/logger.ts (hunk 4 above)
Comment (flavioislima) [reply electron/logger/logger.ts:76]: Yes, I can add a TODO comment to come back here in the future

File: electron/launcher.ts (hunk 1 above)
Comment (CommandMC) [reply electron/launcher.ts:523]: After running the command, you get `stdout` and `stderr`. You can then check for the "MemoryError" string (or anything else you'd like) there, instead of doing it for every legendary/gogdl command

Comment (CommandMC) [reply electron/launcher.ts:523]: IMO, when this function should return an error, it should mean "There was an error running the command", not "There was an error within the program that we were running"
Imagine adding more runners which have similar messages like this, over time you'd just have a giant list of "does the output contain this, then reject with this". That's not scalable

File: electron/legendary/games.ts (hunk 3 above)
Comment (CommandMC) [reply electron/legendary/games.ts:414]: Fair enough
It would be interesting to know why Legendary doesn't do that by default, if it has no negative effects

File: electron/launcher.ts (hunk 1 above)
Comment (flavioislima) [reply electron/launcher.ts:523]: I understand, but like I said this is not an error and the command, even though, fails, it returns a success exit code.
I believe that this memory management could be good to be done on Legendary but maybe there is a reason for that.

I can try to think on another way but it was not that simple to come to a solution for that since we need to intervene on the command to call it again with different parameters

Comment (flavioislima) [reply electron/launcher.ts]: Ok, I fixed that now, the error is handled on Legendary.install like you said 👍🏽

**Comment by CommandMC** [comment]
I'd say showing a dialog if a legendary command failed is fine in general, no need to remove that

**Comment by flavioislima** [comment]
> I'd say showing a dialog if a legendary command failed is fine in general, no need to remove that

Yes, I'm bot removing it. But leaving there is causing the error dialog to appear twice because we already use the log error in other places now.

I will test more tomorrow. And also implementing the error handler for the issue that Ariel opened.

File: electron/legendary/games.ts [hunk 5]
```diff
@@ -724,6 +732,23 @@ class LegendaryGame extends Game {
       return logInfo(`${pattern} killed`, LogPrefix.Legendary)
     })
   }
+
+  public forceUninstall(appName: string, runner: string) {
+    // Modify Legendary installed.json file:
```
Comment (CommandMC) [inline electron/legendary/games.ts:737]: Why not just run `legendary uninstall AppName -y --keep-files`?

Also, since this is in the LegendaryGame class, can't we use `this.appName` for the AppName and just `'Legendary'` as the runner?

Comment (flavioislima) [reply electron/legendary/games.ts:742]: Yes, didnt know about this command. I will try.

Comment (flavioislima) [reply electron/legendary/games.ts:742]: works like charm :)

File: electron/legendary/games.ts [hunk 6]
```diff
@@ -403,16 +403,29 @@ class LegendaryGame extends Game {
...
       logFile: logPath,
       onOutput
     })
 
-    if (res.error) {
-      logError(
-        ['Failed to install', `${this.appName}:`, res.error],
-        LogPrefix.Legendary
+    // try to run the install again with higher memory limit
+    if (res.error === 'MemoryError:') {
```
[the remark this answers is not in the document]
Comment (flavioislima) [reply electron/legendary/games.ts:414]: fair enough. Sent the refactor

**Review by CommandMC — APPROVED** [review]
Alright, now we just gotta find out why the test is failing

**Comment by flavioislima** [comment]
> Alright, now we just gotta find out why the test is failing

Some things in NodeJS makes me crazy.
The test was failing because I was importing `mainWindow` from `main` into the `utils` file. But the error has nothing to do with that, I needed to check the commit that broke the tests and then start changing things until I realized was the import.
🤦🏽

**Comment by CommandMC** [comment]
One thing that makes finding errors like that easier is keeping your commits *very* small. It also keeps everything organized and the number of commits doesn't matter since they're all gonna get squashed at the end anyways

**Comment by flavioislima** [comment]
@CommandMC runtime was missing for me since #1359 was merged, so I sent a new commit to this PR to use the `steamLibraries` to find the runtime now. I think should be fine but maybe would be good to test on a VM with Ubuntu or Pop if you have the time.

**Comment by CommandMC** [comment]
Works fine on my PopOS VM
